/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Productos;
import Entidades.Producto;
import Gestores.GestorInventario;
import Gestores.GestorContactos;
import Vista.FrmMenu;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author equipo
 */
public class FrmProductos extends javax.swing.JFrame {
    private GestorInventario gestorInventario;
    private GestorContactos gestorContactos;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmProductos.class.getName());

    /**
     * Creates new form FrmProductos
     */
    public FrmProductos(GestorInventario gestorCompartido,GestorContactos gestorCont) {
        
        initComponents();
        this.gestorInventario=gestorCompartido;
        this.gestorContactos = gestorCont;
        actualizarTabla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jLProductos = new javax.swing.JLabel();
        btnAgregarProducto = new javax.swing.JButton();
        btnAgregarPedido = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnProcesarCompra = new javax.swing.JButton();

        jMenuItem1.setText("Tarjeta de Almacen");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Modificar Precio Venta");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jPopupMenu1.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Productos");
        setName(""); // NOI18N

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Descripcion", "Precio Compra", "Precio Venta ", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblProductosMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductos);
        if (tblProductos.getColumnModel().getColumnCount() > 0) {
            tblProductos.getColumnModel().getColumn(0).setResizable(false);
            tblProductos.getColumnModel().getColumn(1).setResizable(false);
            tblProductos.getColumnModel().getColumn(2).setResizable(false);
            tblProductos.getColumnModel().getColumn(3).setResizable(false);
            tblProductos.getColumnModel().getColumn(4).setResizable(false);
        }

        jLProductos.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLProductos.setText("Productos");

        btnAgregarProducto.setText("Ingresar Nuevo Producto");
        btnAgregarProducto.addActionListener(this::btnAgregarProductoActionPerformed);

        btnAgregarPedido.setText("Ingresar Nuevo Inventario");
        btnAgregarPedido.addActionListener(this::btnAgregarPedidoActionPerformed);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        btnProcesarCompra.setText("Procesar Compra");
        btnProcesarCompra.addActionListener(this::btnProcesarCompraActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAgregarPedido)
                                .addGap(186, 186, 186)
                                .addComponent(btnProcesarCompra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(377, 377, 377))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLProductos)
                    .addComponent(btnRegresar))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarProducto)
                    .addComponent(btnAgregarPedido)
                    .addComponent(btnProcesarCompra))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        // TODO add your handling code here:
        jdiaIngresarProducto agregar= new jdiaIngresarProducto(this,true);
        agregar.setLocationRelativeTo(this);
        agregar.setVisible(true);
        
        actualizarTabla();

    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
      
        // 1. Extraemos el número de la fila que quedó seleccionada
        int fila = tblProductos.getSelectedRow();
    
        if (fila != -1) { 
        // 2. Extraemos el ID (Columna 0) y el Nombre (Columna 1)
        // Usamos Integer.parseInt y .toString() para evitar errores de casteo
         int idProducto = Integer.parseInt(tblProductos.getValueAt(fila, 0).toString());
            String nombreProducto = tblProductos.getValueAt(fila, 1).toString();
        
        // 3. Abrimos la ventana del Kardex pasándole los datos
        // OJO: Asume que ya creaste el JDialog llamado jdiaKardex
            jdialKardex ventanaKardex = new jdialKardex(this, true, idProducto, nombreProducto, gestorInventario);
            ventanaKardex.setLocationRelativeTo(this);
            ventanaKardex.setVisible(true);
    }
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void tblProductosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseReleased
        // TODO add your handling code here:
            // Verifica si fue clic derecho (Popup Trigger)
        if (evt.isPopupTrigger()) {
        // Calcula la fila en base a las coordenadas del ratón (X, Y)
        int filaSeleccionada = tblProductos.rowAtPoint(evt.getPoint());
        
        // Fuerza a la tabla a seleccionar esa fila visualmente
        if (filaSeleccionada >= 0 && filaSeleccionada < tblProductos.getRowCount()) {
            tblProductos.setRowSelectionInterval(filaSeleccionada, filaSeleccionada);
            
            // Muestra tu menú emergente (asumiendo que lo llamaste popMenuEditar)
            // en la posición exacta del ratón
            jPopupMenu1.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }
    }//GEN-LAST:event_tblProductosMouseReleased

    private void btnAgregarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPedidoActionPerformed
        // TODO add your handling code here:
        // Le pasamos el 'this', el 'true', y los DOS gestores
        jdiaNuevaCompra ventanaCompra = new jdiaNuevaCompra(this, true, gestorInventario, gestorContactos);
        ventanaCompra.setLocationRelativeTo(this);
        ventanaCompra.setVisible(true);
        actualizarTabla();
    }//GEN-LAST:event_btnAgregarPedidoActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // Buscamos el Menú principal en la memoria de Java y lo volvemos a encender
    for (java.awt.Window window : java.awt.Window.getWindows()) {
        if (window instanceof Vista.FrmMenu) {
            window.setVisible(true);
            break;
        }
    }
    
    // Cerramos y destruimos la ventana actual en la que estamos
    this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnProcesarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarCompraActionPerformed
        // TODO add your handling code here:
        // 1. Instanciamos tu nueva ventana pasándole el gestor que contiene las órdenes
        jdialGestionarOrdenes gestionar = new jdialGestionarOrdenes(this, true, gestorInventario);
        gestionar.setLocationRelativeTo(this);
    
        // 2. Mostramos la ventana (El sistema de productos se pausa en esta línea)
        gestionar.setVisible(true);
    
        // 3. Cuando el usuario cierra la gestión, actualizamos el inventario visualmente
        actualizarTabla();
    }//GEN-LAST:event_btnProcesarCompraActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        // 1. Extraemos el número de la fila que quedó seleccionada con el clic derecho
        int fila = tblProductos.getSelectedRow();
        
        if (fila != -1) { 
            // 2. Extraemos el ID del producto (Columna 0)
            int idProducto = Integer.parseInt(tblProductos.getValueAt(fila, 0).toString());
            
            // 3. Abrimos la ventanita pasándole el ID y el Gestor
            jdialPrecioVenta ventanaPrecio = new jdialPrecioVenta(this, true, idProducto, gestorInventario);
            ventanaPrecio.setLocationRelativeTo(this);
            
            // El programa se pausa aquí hasta que el usuario le dé a "Agregar" y se cierre
            ventanaPrecio.setVisible(true);
            
            // 4. Apenas se cierra la ventanita, repintamos la tabla para ver el nuevo precio
            actualizarTabla();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un producto haciendo clic en la fila primero.");
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    // Nuevo método para recibir el texto de la ventana hija
    public void registrarNuevoProducto(String descripcion) {
         // 1. Aquí debes guardar el producto en tu gestor. 
        
        // Adapta esta línea según cómo funcione tu GestorInventario y tu clase Producto:
        Producto nuevoProducto = new Producto(descripcion); // Suponiendo este constructor
        gestorInventario.registrarProducto(nuevoProducto);    // Suponiendo este método

        // 2. UNA VEZ GUARDADO, ahora sí mandamos a actualizar la tabla
        actualizarTabla();
    }
    public void actualizarTabla() {
        // Capturamos el modelo estructural de la tabla (tblClientes)
        DefaultTableModel modelo = (DefaultTableModel) tblProductos.getModel();
       
        
        // Reiniciamos las filas a cero para no duplicar los datos visualmente al recargar
        modelo.setRowCount(0);
        
        // Extraemos la memoria temporal y la recorremos
        List<Producto> lista = gestorInventario.obtenerTodosLosProductos();         
            for (Producto p : lista) {
        // Evaluamos si los datos son null para mostrar un texto vacío "" o un guión "-"
        String txtCompra = (p.getPrecioCompra() == null) ? "Sin asignar" : "s/" + p.getPrecioCompra();
        String txtVenta  = (p.getPrecioVentaBase() == null) ? "Sin asignar" : "s/" + p.getPrecioVentaBase();
        String txtStock  = (p.getStock() == null) ? "0 (Vacio)" : String.valueOf(p.getStock());

        modelo.addRow(new Object[]{
            p.getId(), 
            p.getDescripcion(), 
            txtCompra, // Usamos las variables formateadas
            txtVenta,
            txtStock
        });
        }
        ajustarAnchoColumnas();
    }
     private void ajustarAnchoColumnas() {
    // 1. Extraemos el modelo estructural de las columnas de tu tabla
    javax.swing.table.TableColumnModel modeloColumna = tblProductos.getColumnModel();

    // 2. Recorremos cada una de las columnas
    for (int i = 0; i < modeloColumna.getColumnCount(); i++) {
        int anchoCalculado = 50; // Un ancho mínimo por seguridad

        // A. Revisamos cuánto espacio exige el texto del título de la columna
        javax.swing.table.TableColumn columna = modeloColumna.getColumn(i);
        javax.swing.table.TableCellRenderer rendererCabecera = columna.getHeaderRenderer();
        
        if (rendererCabecera == null) {
            rendererCabecera = tblProductos.getTableHeader().getDefaultRenderer();
        }
        
        java.awt.Component compCabecera = rendererCabecera.getTableCellRendererComponent(
            tblProductos, columna.getHeaderValue(), false, false, 0, i);
        
        anchoCalculado = Math.max(anchoCalculado, compCabecera.getPreferredSize().width);

        // B. Recorremos todas las filas de esa columna para buscar el texto más largo
        for (int j = 0; j < tblProductos.getRowCount(); j++) {
            javax.swing.table.TableCellRenderer rendererCelda = tblProductos.getCellRenderer(j, i);
            java.awt.Component compCelda = rendererCelda.getTableCellRendererComponent(
                tblProductos, tblProductos.getValueAt(j, i), false, false, j, i);
            
            anchoCalculado = Math.max(anchoCalculado, compCelda.getPreferredSize().width);
        }

        // C. Le aplicamos el tamaño ganador a la columna, más 10 píxeles de margen estético
        columna.setPreferredWidth(anchoCalculado + 10);
    }
}
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPedido;
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnProcesarCompra;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLProductos;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProductos;
    // End of variables declaration//GEN-END:variables
}
