/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista.Productos;

/**
 *
 * @author equipo
 */
public class jdialVerDetalle extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jdialVerDetalle.class.getName());

    /**
     * Creates new form jdialVerDetalle
     */
    public jdialVerDetalle(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblProveedor = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalles = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo.setText("Titulo");

        lblProveedor.setText("Proveedor");

        lblEstado.setText("Estado");

        lblTotal.setText("Total");

        tblDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Costo Unitario", "Sub Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDetalles);
        if (tblDetalles.getColumnModel().getColumnCount() > 0) {
            tblDetalles.getColumnModel().getColumn(0).setResizable(false);
            tblDetalles.getColumnModel().getColumn(1).setResizable(false);
            tblDetalles.getColumnModel().getColumn(2).setResizable(false);
            tblDetalles.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addComponent(lblProveedor)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblEstado)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTotal))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado)
                    .addComponent(lblTotal))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void cargarDetalles(Entidades.OrdenCompra orden) {
        // 1. Llenamos las etiquetas (Labels) con los datos generales
        lblTitulo.setText("Detalles de la Orden #" + orden.getCodigo());
        lblProveedor.setText("Proveedor: " + orden.getProveedor().getRazonSocial());
        lblEstado.setText("Estado actual: " + orden.getEstado());

        // 2. Preparamos la tabla para los productos
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblDetalles.getModel();
        modelo.setRowCount(0); // Limpia filas anteriores si las hubiera

        double totalMonto = 0;

        // 3. Recorremos los lotes y llenamos la tabla fila por fila
        for (Entidades.LoteProducto lote : orden.getLotes()) {
            double subtotal = lote.getCantidadIngresada() * lote.getPrecioCompraIndividual();
            totalMonto += subtotal;
            
            modelo.addRow(new Object[]{
                lote.getProducto().getDescripcion(),
                lote.getCantidadIngresada(),
                String.format("S/ %.2f", lote.getPrecioCompraIndividual()),
                String.format("S/ %.2f", subtotal)
            });
        }
        
        // 4. Mostramos el cálculo final
        lblTotal.setText(String.format("Total: S/ %.2f", totalMonto));
    }
    private void ajustarAnchoColumnas() {
       tblDetalles.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
    // 1. Extraemos el modelo estructural de las columnas de tu tabla y su cabecera
    javax.swing.table.TableColumnModel modeloColumna = tblDetalles.getColumnModel();
    javax.swing.table.JTableHeader cabecera = tblDetalles.getTableHeader();

    // 2. Recorremos cada una de las columnas
    for (int i = 0; i < modeloColumna.getColumnCount(); i++) {
        int anchoCalculado = 50; // Un ancho mínimo por seguridad
        javax.swing.table.TableColumn columna = modeloColumna.getColumn(i);

        // --- A. REVISAMOS CUÁNTO ESPACIO EXIGE EL TÍTULO (CABECERA) ---
        if (cabecera != null) {
            // Método 1: Por Renderer (el que ya tenías)
            javax.swing.table.TableCellRenderer rendererCabecera = columna.getHeaderRenderer();
            if (rendererCabecera == null) {
                rendererCabecera = cabecera.getDefaultRenderer();
            }
            java.awt.Component compCabecera = rendererCabecera.getTableCellRendererComponent(tblDetalles, columna.getHeaderValue(), false, false, 0, i);
            
            int anchoPorRenderer = compCabecera.getPreferredSize().width;

            // Método 2: Por FontMetrics (Refuerzo infalible para el texto del título)
            java.awt.FontMetrics fm = cabecera.getFontMetrics(cabecera.getFont());
            String textoTitulo = columna.getHeaderValue() != null ? columna.getHeaderValue().toString() : "";
            // Sumamos 20px extra para asegurar espacio para márgenes o íconos de ordenamiento
            int anchoPorTexto = fm.stringWidth(textoTitulo) + 20; 

            // Nos quedamos con el valor más grande entre el renderer y nuestro cálculo manual
            anchoCalculado = Math.max(anchoCalculado, Math.max(anchoPorRenderer, anchoPorTexto));
        }

        // --- B. RECORREMOS LAS FILAS PARA BUSCAR EL CONTENIDO MÁS LARGO ---
        for (int j = 0; j < tblDetalles.getRowCount(); j++) {
            javax.swing.table.TableCellRenderer rendererCelda = tblDetalles.getCellRenderer(j, i);
            java.awt.Component compCelda = rendererCelda.getTableCellRendererComponent(tblDetalles, tblDetalles.getValueAt(j, i), false, false, j, i);
            
            anchoCalculado = Math.max(anchoCalculado, compCelda.getPreferredSize().width);
        }

        // --- C. APLICAMOS EL TAMAÑO GANADOR ---
        // Le damos 15 píxeles de margen estético general en lugar de 10 para que "respire" mejor
        columna.setPreferredWidth(anchoCalculado + 15);
    }
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblProveedor;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblDetalles;
    // End of variables declaration//GEN-END:variables
}
