/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista.Productos;

import Entidades.LoteProducto;
import Entidades.OrdenCompra;
import Entidades.Producto;
import Entidades.Proveedor;
import Gestores.GestorContactos;
import Gestores.GestorInventario;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author equipo
 */
public class jdiaNuevaCompra extends javax.swing.JDialog {
    private GestorInventario gestorInventario;
    // Nuestra "cesta" temporal de la compra actual
    private List<LoteProducto> carritoTemporal;
    private GestorContactos gestorContactos;
    
    private Producto productoSeleccionadoTemporal = null;
    private Proveedor proveedorSeleccionadoTemporal = null;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jdiaNuevaCompra.class.getName());

    /**
     * Creates new form jdiaNuevaCompra
     */
    public jdiaNuevaCompra(java.awt.Frame parent, boolean modal, GestorInventario gestorInv,GestorContactos gestorCon) {
        super(parent, modal);
        initComponents();
        this.gestorInventario = gestorInv;
        this.gestorContactos = gestorCon;
        this.carritoTemporal = new ArrayList<>();
        // Bloqueo estricto para evitar que el usuario escriba a mano
        txtProductoSeleccionado.setEditable(false);
        txtProveedorSeleccionado.setEditable(false);
      
    }
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCantidad = new javax.swing.JTextField();
        txtPrecioCompra = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAgregarAlCarrito = new javax.swing.JButton();
        btnProcesarCompra = new javax.swing.JButton();
        txtProductoSeleccionado = new javax.swing.JTextField();
        btnBuscarProducto = new javax.swing.JButton();
        txtProveedorSeleccionado = new javax.swing.JTextField();
        btnBuscarProveedor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnQuitarDelCarrito = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtPrecioCompra.addActionListener(this::txtPrecioCompraActionPerformed);

        jLabel1.setText("Cantidad");

        jLabel2.setText("Precio Compra");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Descripcion", "Cantidad", "Precio", "Sub Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        btnAgregarAlCarrito.setText("Agregar");
        btnAgregarAlCarrito.addActionListener(this::btnAgregarAlCarritoActionPerformed);

        btnProcesarCompra.setText("Procesar Compra");
        btnProcesarCompra.addActionListener(this::btnProcesarCompraActionPerformed);

        btnBuscarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search.png"))); // NOI18N
        btnBuscarProducto.addActionListener(this::btnBuscarProductoActionPerformed);

        btnBuscarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search.png"))); // NOI18N
        btnBuscarProveedor.addActionListener(this::btnBuscarProveedorActionPerformed);

        jLabel3.setText("Producto");

        jLabel4.setText("Proveedor");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solicitada", "Pendiente", "Procesada" }));

        jLabel5.setText("Estado");

        btnQuitarDelCarrito.setText("Quitar");
        btnQuitarDelCarrito.addActionListener(this::btnQuitarDelCarritoActionPerformed);

        lblTotal.setText("Total:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarProveedor)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtProveedorSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtProductoSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btnAgregarAlCarrito)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnQuitarDelCarrito)
                        .addGap(27, 27, 27)
                        .addComponent(btnProcesarCompra)
                        .addGap(33, 33, 33)
                        .addComponent(lblTotal)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregarAlCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtProductoSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                    .addComponent(btnBuscarProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuscarProveedor)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtProveedorSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addComponent(txtPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcesarCompra)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btnQuitarDelCarrito)
                    .addComponent(lblTotal))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarAlCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAlCarritoActionPerformed
      try {
        // 1. Validamos que haya usado las lupas
        if (productoSeleccionadoTemporal == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un producto usando la lupa.");
            return;
        }
        if (proveedorSeleccionadoTemporal == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un proveedor antes de empezar la orden.");
            return;
        }

        // 2. Extraemos los números arreglando la coma decimal
        String textoCantidad = txtCantidad.getText().trim();
        String textoPrecio = txtPrecioCompra.getText().trim().replace(",", ".");
        
        int cantidad = Integer.parseInt(textoCantidad);
        double precioCompra = Double.parseDouble(textoPrecio);

        // 3. Creamos el lote
        Entidades.LoteProducto nuevoLote = new Entidades.LoteProducto(cantidad, precioCompra, productoSeleccionadoTemporal);
        carritoTemporal.add(nuevoLote);
        actualizarTablaCarrito();
        
        // 4. ¡LA REGLA DE NEGOCIO! Bloqueamos el botón del proveedor para que no lo cambie
        btnBuscarProveedor.setEnabled(false);
        
        // 5. Limpiamos solo los campos del producto para que ingrese el siguiente
        productoSeleccionadoTemporal = null;
        txtProductoSeleccionado.setText("");
        txtCantidad.setText("");
        txtPrecioCompra.setText("");
        
    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Verifique los datos ingresados.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnAgregarAlCarritoActionPerformed

    private void btnProcesarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarCompraActionPerformed
    if (carritoTemporal.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "El carrito de compras está vacío.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            if(this.proveedorSeleccionadoTemporal == null){
                javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar un proveedor válido.");
                return;
            }

            // 1. Extraemos el estado (que ahora no incluye 'Cancelada' gracias al diseño visual)
            String estadoSeleccionado = cmbEstado.getSelectedItem().toString();
            
            // 2. Creamos la orden
            Entidades.OrdenCompra nuevaOrden = new Entidades.OrdenCompra(java.time.LocalDate.now().toString(), estadoSeleccionado, this.proveedorSeleccionadoTemporal); 
            
            for (Entidades.LoteProducto lote : carritoTemporal) {
                nuevaOrden.agregarLote(lote);
            }
            
            // 3. Registramos
            gestorInventario.registrarOrdenCompra(nuevaOrden);
            
            // 4. Actualizamos el Kardex SOLO si la mercadería ya entró al almacén
            if (estadoSeleccionado.equals("Procesada") || estadoSeleccionado.equals("Abonada")) {
                gestorInventario.procesarStockKardex(nuevaOrden.getCodigo());
            }
            
            javax.swing.JOptionPane.showMessageDialog(this, "¡Compra registrada con éxito como: " + estadoSeleccionado + "!");
            this.dispose(); 
            
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al procesar: " + ex.getMessage(), "Error Crítico", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnProcesarCompraActionPerformed

    private void txtPrecioCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioCompraActionPerformed

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        // TODO add your handling code here:
        // Abrimos el buscador pasándole el gestor
        jdialBuscarProducto buscador = new jdialBuscarProducto(null, true, gestorInventario);
        buscador.setLocationRelativeTo(this);
        buscador.setVisible(true); // El código se pausa aquí hasta que la ventana se cierre

        // Cuando se cierra, le pedimos a la ventana qué producto eligió el usuario
        Entidades.Producto prodEncontrado = buscador.getProductoSeleccionado();
    
        if (prodEncontrado != null) {
          this.productoSeleccionadoTemporal = prodEncontrado;
          // Mostramos el nombre en la caja de texto visual (txtProductoSeleccionado)
         txtProductoSeleccionado.setText(prodEncontrado.getDescripcion()); 
        }
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void btnBuscarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProveedorActionPerformed
        // TODO add your handling code here:
        // Lógica idéntica, pero abriendo jdiaBuscarProveedor y pasándole el gestorContactos
        jdialBuscarProveedor buscador = new jdialBuscarProveedor(null, true, gestorContactos);
        buscador.setLocationRelativeTo(this);
        buscador.setVisible(true);

        Entidades.Proveedor provEncontrado = buscador.getProveedorSeleccionado();
    
        if (provEncontrado != null) {
            this.proveedorSeleccionadoTemporal = provEncontrado;
            txtProveedorSeleccionado.setText(provEncontrado.getRazonSocial()); 
        }
    }//GEN-LAST:event_btnBuscarProveedorActionPerformed

    private void btnQuitarDelCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarDelCarritoActionPerformed
            // 1. Verificamos qué fila seleccionó el usuario en la tabla
        int fila = jTable1.getSelectedRow();

        if (fila != -1) {
            // 2. Lo eliminamos de nuestra lista temporal
            carritoTemporal.remove(fila);

            // 3. Repintamos la tabla
            actualizarTablaCarrito();

            // 4. Si el carrito se queda vacío, le permitimos cambiar de proveedor otra vez
            if (carritoTemporal.isEmpty()) {
                btnBuscarProveedor.setEnabled(true);
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un producto de la tabla para quitarlo.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnQuitarDelCarritoActionPerformed

    private void actualizarTablaCarrito() {
        // 1. Capturamos el modelo y limpiamos el lienzo
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0); 

        // Creamos una variable para ir acumulando el total de la orden
        double totalGeneral = 0.0;

        // 2. Recorremos la cesta de compras
        for (Entidades.LoteProducto lote : carritoTemporal) {
            
            // 3. Calculamos la matemática (Subtotal del lote)
            double subtotal = lote.getCantidadIngresada() * lote.getPrecioCompraIndividual();
            
            // Sumamos el subtotal al total general
            totalGeneral += subtotal;

            // 4. Pintamos la fila extrayendo los datos del objeto
            modelo.addRow(new Object[]{
                lote.getProducto().getId(),                             // Columna 0: ID
                lote.getProducto().getDescripcion(),                    // Columna 1: Nombre
                lote.getCantidadIngresada(),                            // Columna 2: Cantidad
                String.format("S/ %.2f", lote.getPrecioCompraIndividual()), // Columna 3: Costo Unit.
                String.format("S/ %.2f", subtotal)                      // Columna 4: Subtotal
            });
        }
        
        // 5. Finalmente, imprimimos el total general en el JLabel
        lblTotal.setText(String.format("Total: S/ %.2f", totalGeneral));
    }
     
    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAlCarrito;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnBuscarProveedor;
    private javax.swing.JButton btnProcesarCompra;
    private javax.swing.JButton btnQuitarDelCarrito;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtPrecioCompra;
    private javax.swing.JTextField txtProductoSeleccionado;
    private javax.swing.JTextField txtProveedorSeleccionado;
    // End of variables declaration//GEN-END:variables
}
