/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista.Productos;

import Gestores.GestorInventario;

/**
 *
 * @author equipo
 */
public class jdialPrecioVenta extends javax.swing.JDialog {
     private GestorInventario gestor;
    private int idProducto;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jdialPrecioVenta.class.getName());

    /**
     * Creates new form jdialPrecioVenta
     */
   

    public jdialPrecioVenta(java.awt.Frame parent, boolean modal, int idProducto, GestorInventario gestorInv) {
        super(parent, modal);
        initComponents();
        this.idProducto = idProducto;
        this.gestor = gestorInv;
        this.setTitle("Modificar Precio");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtPrecio = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(txtPrecio);

        jLabel1.setText("Ingresa Nuevo Precio");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btnAgregar)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregar)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Extraemos el texto y prevenimos el error de la coma decimal
            String textoPrecio = txtPrecio.getText().trim().replace(",", ".");
            
            if (textoPrecio.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "El campo de precio no puede estar vacío.");
                return;
            }
            
            double nuevoPrecio = Double.parseDouble(textoPrecio);
            
            // 2. Buscamos el producto exacto usando el ID que nos pasaron
            Entidades.Producto producto = gestor.buscarProductoPorId(this.idProducto);
            
            if (producto != null) {
                // 3. Modificamos su precio de venta
                producto.setPrecioVentaBase(nuevoPrecio);
                
                // 4. Guardamos el cambio en el Gestor
                gestor.actualizarProducto(producto);
                
                javax.swing.JOptionPane.showMessageDialog(this, "Precio de venta actualizado con éxito.");
                
                // 5. Cerramos la ventanita automáticamente
                this.dispose();
            }
            
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un valor numérico válido.", "Error de Formato", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException ex) {
            // Aquí atrapamos el "grito" (throw) que lanza la entidad Producto
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Validación de Negocio", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane txtPrecio;
    // End of variables declaration//GEN-END:variables
}
