/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista.Productos;

import Gestores.GestorInventario;

/**
 *
 * @author equipo
 */
public class jdialGestionarOrdenes extends javax.swing.JDialog {
    private GestorInventario gestor;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jdialGestionarOrdenes.class.getName());
    
    /**
     * Creates new form jdialGestionarOrdenes
     */
    public jdialGestionarOrdenes(java.awt.Frame parent, boolean modal, GestorInventario gestorInv) {
      super(parent, modal);
        initComponents();
        this.gestor = gestorInv;
        
        // 1. Apagamos los botones para obligar al usuario a hacer clic en la tabla primero
        btnProcesar.setEnabled(false);
        btnCancelar.setEnabled(false);
        
        // 2. Llenamos la tabla
        actualizarTabla();
    }
    private void actualizarTabla() {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblOrdenes.getModel();
        modelo.setRowCount(0); 

        java.util.List<Entidades.OrdenCompra> lista = gestor.obtenerHistorialCompras();
        
        for (Entidades.OrdenCompra o : lista) {
            // Calculamos el monto total de esta orden sumando sus lotes internos
            double montoTotal = 0;
            for (Entidades.LoteProducto lote : o.getLotes()) {
                montoTotal += lote.getCantidadIngresada() * lote.getPrecioCompraIndividual();
            }
            
            // Orden exacto de tu diseño: Fecha, Codigo, Proveedor, Monto Total, Estado
            modelo.addRow(new Object[]{
                o.getFechaIngreso(),
                o.getCodigo(),
                o.getProveedor().getRazonSocial(),
                String.format("S/ %.2f", montoTotal),
                o.getEstado()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrdenes = new javax.swing.JTable();
        btnProcesar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblOrdenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Codigo", "Proveedor", "Monto Total", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrdenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblOrdenesMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblOrdenes);
        if (tblOrdenes.getColumnModel().getColumnCount() > 0) {
            tblOrdenes.getColumnModel().getColumn(0).setResizable(false);
            tblOrdenes.getColumnModel().getColumn(1).setResizable(false);
            tblOrdenes.getColumnModel().getColumn(2).setResizable(false);
            tblOrdenes.getColumnModel().getColumn(3).setResizable(false);
            tblOrdenes.getColumnModel().getColumn(4).setResizable(false);
        }

        btnProcesar.setText("Procesar");
        btnProcesar.addActionListener(this::btnProcesarActionPerformed);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Ordenes de Compra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnProcesar)
                        .addGap(152, 152, 152)
                        .addComponent(btnCancelar)
                        .addGap(171, 171, 171))))
            .addGroup(layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcesar)
                    .addComponent(btnCancelar))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblOrdenesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrdenesMouseReleased
        // TODO add your handling code here:
        int fila = tblOrdenes.getSelectedRow();
        
        if (fila != -1) {
            // Si el usuario seleccionó una fila válida, encendemos ambos botones
            btnProcesar.setEnabled(true);
            btnCancelar.setEnabled(true);
        }
    }//GEN-LAST:event_tblOrdenesMouseReleased

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        // TODO add your handling code here:
        int fila = tblOrdenes.getSelectedRow();
        
        if (fila != -1) {
            try {
                // Tu columna de 'Codigo' es la posición 1 (la segunda columna)
                int codigo = Integer.parseInt(tblOrdenes.getValueAt(fila, 1).toString());
                
                // Disparamos la lógica que ya habías puesto en tu gestor
                gestor.avanzarEstadoOrden(codigo);
                
                javax.swing.JOptionPane.showMessageDialog(this, "Orden avanzada/procesada con éxito.");
                this.dispose(); // Cierra la ventana como pediste
                
            } catch (Exception ex) {
                // Si intenta avanzar una orden que ya está completada o cancelada, mostrará tu error
                javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnProcesarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        int fila = tblOrdenes.getSelectedRow();
        
        if (fila != -1) {
            try {
                int codigo = Integer.parseInt(tblOrdenes.getValueAt(fila, 1).toString());
                
                gestor.cancelarOrden(codigo);
                
                javax.swing.JOptionPane.showMessageDialog(this, "La orden ha sido cancelada.");
                this.dispose(); // Cierra la ventana
                
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error Crítico", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnProcesar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOrdenes;
    // End of variables declaration//GEN-END:variables
}
