/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Entidades.DetallePedido;
import Entidades.Pedido;
import Gestores.GestorVentas;

/**
 *
 * @author equipo
 */
public class FmrGestionPedidos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FmrGestionPedidos.class.getName());
    private GestorVentas gestorVentas;
    
    /**
     * Creates new form FmrGestionPedidos
     */
    public FmrGestionPedidos(GestorVentas gestor) {
        initComponents();
        this.gestorVentas = gestor;
        
        // Apagamos los botones de acción hasta que seleccionen una fila
        btnProcesar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnCancelar.setEnabled(false); // Nuevo botón para ventas
        
        actualizarTabla();
    }
    private void actualizarTabla() {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblPedidos.getModel();
        modelo.setRowCount(0); 

        // Traemos el historial de ventas
        java.util.List<Pedido> lista = gestorVentas.obtenerHistorialPedidos();
        
        for (Pedido p : lista) {
            double montoTotal = 0;
            // En ventas se usan Detalles de Pedido, no Lotes
            for (DetallePedido detalle : p.getDetalles()) {
                montoTotal += detalle.getCantidadVendida() * detalle.getPrecioVentaCongelado();
            }
            
            // Ordenamos: Fecha, Codigo, Cliente, Monto Total, Estado
           modelo.addRow(new Object[]{
                p.getCodigo(), 
                p.getCliente().getNombre(), 
                p.getFechaEmision(),
                p.getFechaRecepcion(),
                String.format("S/ %.2f", montoTotal),
                p.getEstado(),
                p.getTipoVenta(),
                String.format("S/ %.2f", p.getDeudaPendiente()) // Usamos la deuda en lugar de FechaPago
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnProcesar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Cliente", "Emision", "Recepcion", "Total", "Estado", "Tipo Venta", "FechaPago"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPedidos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPedidosMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblPedidosMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblPedidos);
        if (tblPedidos.getColumnModel().getColumnCount() > 0) {
            tblPedidos.getColumnModel().getColumn(0).setResizable(false);
            tblPedidos.getColumnModel().getColumn(1).setResizable(false);
            tblPedidos.getColumnModel().getColumn(2).setResizable(false);
            tblPedidos.getColumnModel().getColumn(3).setResizable(false);
            tblPedidos.getColumnModel().getColumn(4).setResizable(false);
            tblPedidos.getColumnModel().getColumn(5).setResizable(false);
            tblPedidos.getColumnModel().getColumn(6).setResizable(false);
            tblPedidos.getColumnModel().getColumn(7).setResizable(false);
        }

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Pedidos");
        jLabel1.setToolTipText("");

        btnProcesar.setText("Procesar");
        btnProcesar.addActionListener(this::btnProcesarActionPerformed);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnProcesar)
                        .addGap(320, 320, 320)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnRegresar)
                            .addGap(110, 110, 110)
                            .addComponent(jLabel1))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcesar)
                    .addComponent(btnCancelar))
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // Buscamos el Menú principal en la memoria de Java y lo volvemos a encender
    for (java.awt.Window window : java.awt.Window.getWindows()) {
        if (window instanceof Vista.FrmMenu) {
            window.setVisible(true);
            break;
        }
    }
    
    // Cerramos y destruimos la ventana actual en la que estamos
    this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void tblPedidosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPedidosMouseReleased
        // TODO add your handling code here:
        int fila = tblPedidos.getSelectedRow();
        if (fila != -1) {
            btnProcesar.setEnabled(true);
            btnCancelar.setEnabled(true);
            
        }
    }//GEN-LAST:event_tblPedidosMouseReleased

    private void tblPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPedidosMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int fila = tblPedidos.getSelectedRow();
            if (fila != -1) {
                int codigo = Integer.parseInt(tblPedidos.getValueAt(fila, 0).toString());
                
                Pedido pedidoCompleto = gestorVentas.obtenerDetallesDePedido(codigo);
                
                if (pedidoCompleto != null) {
                    // Necesitarás crear un jdialVerDetalleVenta similar al de compras
                    jdialDetalleVenta ventanaDetalles = new jdialDetalleVenta(this, true);
                    ventanaDetalles.cargarDetalles(pedidoCompleto);
                    ventanaDetalles.setLocationRelativeTo(this);
                    ventanaDetalles.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_tblPedidosMouseClicked

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        // TODO add your handling code here:
        int fila = tblPedidos.getSelectedRow();
        if (fila != -1) {
            try {
                // 1. Obtenemos el código del pedido de la primera columna (índice 0)
                int codigo = Integer.parseInt(tblPedidos.getValueAt(fila, 0).toString());
                
                // 2. Traemos el pedido completamente fresco desde la base de datos
                Pedido pedidoCompleto = gestorVentas.obtenerDetallesDePedido(codigo);

                if (pedidoCompleto != null) {
                    if (pedidoCompleto.getDeudaPendiente() > 0) {
                        // 3. Abrimos nuestra nueva ventana de caja
                        jdialProcesarVenta caja = new jdialProcesarVenta(this, true);
                        caja.prepararCobro(pedidoCompleto, gestorVentas);
                        caja.setLocationRelativeTo(this);
                        
                        // El programa principal se pausa aquí hasta que la ventana de caja se cierre
                        caja.setVisible(true); 
                        
                        // 4. Al cerrarse la caja, actualizamos la tabla para ver el saldo en cero
                        actualizarTabla(); 
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(this, "Este pedido ya está totalmente pagado.", "Aviso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al abrir cobro: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnProcesarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        int fila = tblPedidos.getSelectedRow();
        if (fila != -1) {
            try {
                int codigo = Integer.parseInt(tblPedidos.getValueAt(fila, 0).toString());
                gestorVentas.cancelarPedido(codigo);
                javax.swing.JOptionPane.showMessageDialog(this, "El pedido ha sido cancelado.");
                actualizarTabla();
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error Crítico", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
   private void ajustarAnchoColumnas() {
       tblPedidos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
    // 1. Extraemos el modelo estructural de las columnas de tu tabla y su cabecera
    javax.swing.table.TableColumnModel modeloColumna = tblPedidos.getColumnModel();
    javax.swing.table.JTableHeader cabecera = tblPedidos.getTableHeader();

    // 2. Recorremos cada una de las columnas
    for (int i = 0; i < modeloColumna.getColumnCount(); i++) {
        int anchoCalculado = 50; // Un ancho mínimo por seguridad
        javax.swing.table.TableColumn columna = modeloColumna.getColumn(i);

        // --- A. REVISAMOS CUÁNTO ESPACIO EXIGE EL TÍTULO (CABECERA) ---
        if (cabecera != null) {
            // Método 1: Por Renderer (el que ya tenías)
            javax.swing.table.TableCellRenderer rendererCabecera = columna.getHeaderRenderer();
            if (rendererCabecera == null) {
                rendererCabecera = cabecera.getDefaultRenderer();
            }
            java.awt.Component compCabecera = rendererCabecera.getTableCellRendererComponent(
                tblPedidos, columna.getHeaderValue(), false, false, 0, i);
            
            int anchoPorRenderer = compCabecera.getPreferredSize().width;

            // Método 2: Por FontMetrics (Refuerzo infalible para el texto del título)
            java.awt.FontMetrics fm = cabecera.getFontMetrics(cabecera.getFont());
            String textoTitulo = columna.getHeaderValue() != null ? columna.getHeaderValue().toString() : "";
            // Sumamos 20px extra para asegurar espacio para márgenes o íconos de ordenamiento
            int anchoPorTexto = fm.stringWidth(textoTitulo) + 20; 

            // Nos quedamos con el valor más grande entre el renderer y nuestro cálculo manual
            anchoCalculado = Math.max(anchoCalculado, Math.max(anchoPorRenderer, anchoPorTexto));
        }

        // --- B. RECORREMOS LAS FILAS PARA BUSCAR EL CONTENIDO MÁS LARGO ---
        for (int j = 0; j < tblPedidos.getRowCount(); j++) {
            javax.swing.table.TableCellRenderer rendererCelda = tblPedidos.getCellRenderer(j, i);
            java.awt.Component compCelda = rendererCelda.getTableCellRendererComponent(
                tblPedidos, tblPedidos.getValueAt(j, i), false, false, j, i);
            
            anchoCalculado = Math.max(anchoCalculado, compCelda.getPreferredSize().width);
        }

        // --- C. APLICAMOS EL TAMAÑO GANADOR ---
        // Le damos 15 píxeles de margen estético general en lugar de 10 para que "respire" mejor
        columna.setPreferredWidth(anchoCalculado + 15);
    }
}
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnProcesar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPedidos;
    // End of variables declaration//GEN-END:variables
}
