/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Entidades.DetallePedido;
import Entidades.Pedido;
import Gestores.GestorVentas;

/**
 *
 * @author equipo
 */
public class FmrGestionPedidos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FmrGestionPedidos.class.getName());
    private GestorVentas gestorVentas;
    
    /**
     * Creates new form FmrGestionPedidos
     */
    public FmrGestionPedidos(GestorVentas gestor) {
       initComponents();
        
      
        
        this.gestorVentas = gestor;
        
        // Apagamos los botones de acción hasta que seleccionen una fila
        
        btnCancelar.setEnabled(false);
        btnEntregar.setEnabled(false);
        
        
        actualizarTabla();
    }
    private void actualizarTabla() {
    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblPedidos.getModel();
    modelo.setRowCount(0); 

    // Traemos el historial (Solo cabeceras, sin productos)
    java.util.List<Entidades.Pedido> lista = gestorVentas.obtenerHistorialPedidos();
    
    for (Entidades.Pedido p : lista) {
        
        // Le pedimos al Gestor que vaya a la BD y llene la lista de productos de este pedido
        Entidades.Pedido pedidoCompleto = gestorVentas.obtenerDetallesDePedido(p.getCodigo());
        
        // Delegamos la operación matemática a la Entidad.
        double montoTotal = (pedidoCompleto != null) ? pedidoCompleto.getTotalPedido() : 0.0;
        
        // ORDEN EXACTO PARA TUS COLUMNAS:
        // [0]Codigo, [1]Cliente, [2]Emision, [3]Recepcion, [4]Total, [5]Estado, [6]Tipo, [7]FechaPago, [8]Deuda
        modelo.addRow(new Object[]{
            p.getCodigo(), 
            p.getCliente().getNombre(), 
            p.getFechaEmision(),
            p.getFechaRecepcion(),
            String.format("S/ %.2f", montoTotal), // Total (Columna 4)
            p.getEstado(),
            p.getTipoVenta(),
            p.getFechaLimitePago(),               // FechaPago (Columna 7)
            String.format("S/ %.2f", p.getDeudaPendiente()) // Deuda (Columna 8)
        });
    }
    
    ajustarAnchoColumnas();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnLimpiarCancelados = new javax.swing.JButton();
        btnEntregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Cliente", "Emision", "Recepcion", "Total", "Estado", "Tipo Venta", "FechaPago", "Deuda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPedidos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPedidosMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblPedidosMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblPedidos);
        if (tblPedidos.getColumnModel().getColumnCount() > 0) {
            tblPedidos.getColumnModel().getColumn(0).setResizable(false);
            tblPedidos.getColumnModel().getColumn(1).setResizable(false);
            tblPedidos.getColumnModel().getColumn(2).setResizable(false);
            tblPedidos.getColumnModel().getColumn(3).setResizable(false);
            tblPedidos.getColumnModel().getColumn(4).setResizable(false);
            tblPedidos.getColumnModel().getColumn(5).setResizable(false);
            tblPedidos.getColumnModel().getColumn(6).setResizable(false);
            tblPedidos.getColumnModel().getColumn(7).setResizable(false);
            tblPedidos.getColumnModel().getColumn(8).setResizable(false);
        }

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Pedidos");
        jLabel1.setToolTipText("");

        btnCancelar.setText("Cancelar Pedido");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnLimpiarCancelados.setText("Eliminar Cancelados");
        btnLimpiarCancelados.addActionListener(this::btnLimpiarCanceladosActionPerformed);

        btnEntregar.setText("Confirmar entrega");
        btnEntregar.addActionListener(this::btnEntregarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEntregar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarCancelados, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegresar)
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnLimpiarCancelados)
                    .addComponent(btnEntregar))
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // Buscamos el Menú principal en la memoria de Java y lo volvemos a encender
    for (java.awt.Window window : java.awt.Window.getWindows()) {
        if (window instanceof Vista.FrmMenu) {
            window.setVisible(true);
            break;
        }
    }
    
    // Cerramos y destruimos la ventana actual en la que estamos
    this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void tblPedidosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPedidosMouseReleased
        // TODO add your handling code here:
        int fila = tblPedidos.getSelectedRow();
        if (fila != -1) {
            
            btnCancelar.setEnabled(true);
            btnEntregar.setEnabled(true);
            
            
        }
    }//GEN-LAST:event_tblPedidosMouseReleased

    private void tblPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPedidosMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int fila = tblPedidos.getSelectedRow();
            if (fila != -1) {
                int codigo = Integer.parseInt(tblPedidos.getValueAt(fila, 0).toString());
                
                Pedido pedidoCompleto = gestorVentas.obtenerDetallesDePedido(codigo);
                
                if (pedidoCompleto != null) {
                    // Necesitarás crear un jdialVerDetalleVenta similar al de compras
                    jdialDetalleVenta ventanaDetalles = new jdialDetalleVenta(this, true);
                    ventanaDetalles.cargarDetalles(pedidoCompleto);
                    ventanaDetalles.setLocationRelativeTo(this);
                    ventanaDetalles.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_tblPedidosMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        int fila = tblPedidos.getSelectedRow();
        if (fila != -1) {
            try {
                int codigo = Integer.parseInt(tblPedidos.getValueAt(fila, 0).toString());
                gestorVentas.cancelarPedido(codigo);
                javax.swing.JOptionPane.showMessageDialog(this, "El pedido ha sido cancelado.");
                actualizarTabla();
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error Crítico", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLimpiarCanceladosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCanceladosActionPerformed
        // TODO add your handling code here:
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this, 
        "¿Seguro que desea eliminar permanentemente todos los pedidos en estado 'Cancelado'?", 
        "Limpieza del Sistema", javax.swing.JOptionPane.YES_NO_OPTION);
        
    if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
        try {
            gestorVentas.eliminarPedidosCancelados();
            javax.swing.JOptionPane.showMessageDialog(this, "Limpieza de pedidos cancelados completada exitosamente.");
            actualizarTabla();
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnLimpiarCanceladosActionPerformed

    private void btnEntregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregarActionPerformed
        int fila = tblPedidos.getSelectedRow();
        if (fila != -1) {
            try {
                // 1. Obtenemos el código del pedido seleccionado
                int codigo = Integer.parseInt(tblPedidos.getValueAt(fila, 0).toString());
                
                // 2. Traemos el pedido para verificar su estado actual
                Pedido pedidoCompleto = gestorVentas.obtenerDetallesDePedido(codigo);
                
                if (pedidoCompleto != null) {
                    if (pedidoCompleto.getEstado().equalsIgnoreCase("Entregado")) {
                        javax.swing.JOptionPane.showMessageDialog(this, "El pedido ya se encuentra entregado.", "Aviso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                        return;
                    }
                    if (pedidoCompleto.getEstado().equalsIgnoreCase("Cancelado")) {
                        javax.swing.JOptionPane.showMessageDialog(this, "No se puede entregar un pedido cancelado.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    
                    // 3. Confirmación de seguridad
                    int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this, 
                        "¿Estás seguro de marcar este pedido como Entregado? Esto descontará el stock del inventario.", 
                        "Confirmar Entrega", javax.swing.JOptionPane.YES_NO_OPTION);
                        
                    if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
                        // 4. Llamamos al método que avanza el estado y descuenta el stock (el que editamos antes)
                        gestorVentas.avanzarEstadoPedido(codigo);
                        
                        javax.swing.JOptionPane.showMessageDialog(this, "Pedido entregado con éxito. El inventario ha sido actualizado.");
                        actualizarTabla();
                    }
                }
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al entregar el pedido: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_btnEntregarActionPerformed

    /**
     * @param args the command line arguments
     */
   private void ajustarAnchoColumnas() {
       tblPedidos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
    // 1. Extraemos el modelo estructural de las columnas de tu tabla y su cabecera
    javax.swing.table.TableColumnModel modeloColumna = tblPedidos.getColumnModel();
    javax.swing.table.JTableHeader cabecera = tblPedidos.getTableHeader();

    // 2. Recorremos cada una de las columnas
    for (int i = 0; i < modeloColumna.getColumnCount(); i++) {
        int anchoCalculado = 50; // Un ancho mínimo por seguridad
        javax.swing.table.TableColumn columna = modeloColumna.getColumn(i);

        // --- A. REVISAMOS CUÁNTO ESPACIO EXIGE EL TÍTULO (CABECERA) ---
        if (cabecera != null) {
            // Método 1: Por Renderer (el que ya tenías)
            javax.swing.table.TableCellRenderer rendererCabecera = columna.getHeaderRenderer();
            if (rendererCabecera == null) {
                rendererCabecera = cabecera.getDefaultRenderer();
            }
            java.awt.Component compCabecera = rendererCabecera.getTableCellRendererComponent(
                tblPedidos, columna.getHeaderValue(), false, false, 0, i);
            
            int anchoPorRenderer = compCabecera.getPreferredSize().width;

            // Método 2: Por FontMetrics (Refuerzo infalible para el texto del título)
            java.awt.FontMetrics fm = cabecera.getFontMetrics(cabecera.getFont());
            String textoTitulo = columna.getHeaderValue() != null ? columna.getHeaderValue().toString() : "";
            // Sumamos 20px extra para asegurar espacio para márgenes o íconos de ordenamiento
            int anchoPorTexto = fm.stringWidth(textoTitulo) + 20; 

            // Nos quedamos con el valor más grande entre el renderer y nuestro cálculo manual
            anchoCalculado = Math.max(anchoCalculado, Math.max(anchoPorRenderer, anchoPorTexto));
        }

        // --- B. RECORREMOS LAS FILAS PARA BUSCAR EL CONTENIDO MÁS LARGO ---
        for (int j = 0; j < tblPedidos.getRowCount(); j++) {
            javax.swing.table.TableCellRenderer rendererCelda = tblPedidos.getCellRenderer(j, i);
            java.awt.Component compCelda = rendererCelda.getTableCellRendererComponent(
                tblPedidos, tblPedidos.getValueAt(j, i), false, false, j, i);
            
            anchoCalculado = Math.max(anchoCalculado, compCelda.getPreferredSize().width);
        }

        // --- C. APLICAMOS EL TAMAÑO GANADOR ---
        // Le damos 15 píxeles de margen estético general en lugar de 10 para que "respire" mejor
        columna.setPreferredWidth(anchoCalculado + 15);
    }
}
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEntregar;
    private javax.swing.JButton btnLimpiarCancelados;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPedidos;
    // End of variables declaration//GEN-END:variables
}
