/*
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Gestores.GestorContactos;
import Gestores.GestorInventario;
import Gestores.GestorVentas;

/**
 *
 * @author equipo
 */
public class FrmAreaVentas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmAreaVentas.class.getName());
    private GestorVentas gestorVentas;
    private GestorContactos gestorContactos;
    private GestorInventario gestorInventario;

    /**
     * Creates new form FrmAreaVentas
     */
    public FrmAreaVentas(GestorVentas gVentas, GestorContactos gContactos, GestorInventario gInv) {
        initComponents();
        this.gestorVentas = gVentas;
        this.gestorContactos = gContactos;
        this.gestorInventario = gInv;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGenerarPedido = new javax.swing.JButton();
        btnGestionarPedido = new javax.swing.JButton();
        btnGestionarClientes = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGenerarPedido.setText("Generar nuevo pedido");
        btnGenerarPedido.addActionListener(this::btnGenerarPedidoActionPerformed);

        btnGestionarPedido.setText("Gestionar pedidos");
        btnGestionarPedido.addActionListener(this::btnGestionarPedidoActionPerformed);

        btnGestionarClientes.setText("Gestionar clientes");
        btnGestionarClientes.addActionListener(this::btnGestionarClientesActionPerformed);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGestionarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGestionarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGenerarPedido)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnRegresar)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(18, 18, 18)
                .addComponent(btnGenerarPedido)
                .addGap(18, 18, 18)
                .addComponent(btnGestionarPedido)
                .addGap(18, 18, 18)
                .addComponent(btnGestionarClientes)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarClientesActionPerformed
        // TODO add your handling code here:
        // Reutilizamos tu ventana FrmClientes exacta que ya tienes creada
        FrmClientes ventanaClientes = new FrmClientes(this.gestorContactos);
        ventanaClientes.setLocationRelativeTo(this);
        ventanaClientes.setVisible(true);
        this.dispose(); // Cerramos esta para ir a clientes
    }//GEN-LAST:event_btnGestionarClientesActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        // Código universal para regresar al Menú
        for (java.awt.Window window : java.awt.Window.getWindows()) {
            if (window instanceof FrmMenu) {
                window.setVisible(true);
                break;
            }
        }
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnGenerarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarPedidoActionPerformed
        // TODO add your handling code here:
        // Instanciamos y abrimos la ventana del carrito de compras
        FrmPedido ventanaPedido = new FrmPedido(this.gestorVentas, this.gestorContactos, this.gestorInventario);
        ventanaPedido.setLocationRelativeTo(this);
        ventanaPedido.setVisible(true);
        
        this.dispose();
        
        // Cerramos el menú actual de ventas
        this.dispose();
    }//GEN-LAST:event_btnGenerarPedidoActionPerformed

    private void btnGestionarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarPedidoActionPerformed
        // TODO add your handling code here:
        // Instanciamos y abrimos la ventana de gestión de pedidos
        //FmrGestionPedidos ventanaGestion = new FmrGestionPedidos();
        //ventanaGestion.setLocationRelativeTo(this);
        //ventanaGestion.setVisible(true);
        
        // Cerramos el menú actual de ventas
        this.dispose();
        
    }//GEN-LAST:event_btnGestionarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarPedido;
    private javax.swing.JButton btnGestionarClientes;
    private javax.swing.JButton btnGestionarPedido;
    private javax.swing.JButton btnRegresar;
    // End of variables declaration//GEN-END:variables
}
