/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Entidades.Cliente;
import Gestores.GestorContactos;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author equipo
 */
public class FrmClientes extends javax.swing.JFrame {
    // 1. El atributo que conectará esta ventana con la memoria global de tu sistema
    private GestorContactos gestor;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmClientes.class.getName());

    /**
     * Creates new form FrmClientes
     */
   // 2. El Constructor: Modifícalo para que exija el Gestor como parámetro
    public FrmClientes(GestorContactos gestorCompartido) {
        initComponents(); // Método intocable autogenerado por NetBeans
        
        // Asignamos el gestor que viene desde el Menú a nuestra variable interna
        this.gestor = gestorCompartido;
        
        // Ejecutamos la lógica para llenar la tabla apenas la ventana nazca
        //actualizarTabla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textCodigo = new java.awt.TextField();
        textNombre = new java.awt.TextField();
        textCorreo = new java.awt.TextField();
        textDireccion = new java.awt.TextField();
        textNumero = new java.awt.TextField();
        labelCodigo = new java.awt.Label();
        labelNombre = new java.awt.Label();
        labelCorreo = new java.awt.Label();
        labelNumero = new java.awt.Label();
        labelDireccion = new java.awt.Label();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textNumero.addActionListener(this::textNumeroActionPerformed);

        labelCodigo.setText("Ingrese DNI");

        labelNombre.setText("Ingrese Nombre");

        labelCorreo.setText("Ingrese Correo");

        labelNumero.setText("Ingrese Numero");

        labelDireccion.setText("Ingrese Dirección");

        btnGuardar.setText("Registrar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(btnGuardar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)))
                    .addComponent(labelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(331, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnGuardar)
                .addContainerGap(280, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNumeroActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try{
            int codigo=Integer.parseInt(textCodigo.getText());
            String nombre=textNombre.getText();
            String correo=textCorreo.getText();
            String direccion=textDireccion.getText();
            String numero=textNumero.getText();
            
            // B. Instanciación: Ejecución del "molde" y sus reglas de validación
            Cliente nuevoCliente=new Cliente(codigo,nombre,direccion,correo,numero);
            
            // C. Delegación: El controlador asume el trabajo de verificar duplicados
            gestor.registrarCliente(nuevoCliente);
            
            // D. Éxito: Feedback al usuario y refresco de pantalla
            JOptionPane.showMessageDialog(this, "Cliente registrado con éxito.");
           // limpiarCajas();
            //actualizarTabla();
        
        }
        catch(NumberFormatException ex){
            // Intercepción si el usuario teclea letras en el campo del código
            JOptionPane.showMessageDialog(this, "Error: El código debe ser un número válido.", "Error de Formato", JOptionPane.ERROR_MESSAGE);  
        }
        catch(IllegalArgumentException ex){// Intercepción de las reglas de negocio (textos vacíos, duplicados, etc.)
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de Validación", JOptionPane.WARNING_MESSAGE);
        
        }
        
        
    }//GEN-LAST:event_btnGuardarActionPerformed
      // 4. Lógica de Lectura Visual (El puente entre la lista y la pantalla)
    /*private void actualizarTabla() {
        // Capturamos el modelo estructural de la tabla (tblClientes)
        DefaultTableModel modelo = (DefaultTableModel) tblClientes.getModel();
       
        
        // Reiniciamos las filas a cero para no duplicar los datos visualmente al recargar
        modelo.setRowCount(0);
        
        // Extraemos la memoria temporal y la recorremos
        List<Cliente> lista = gestor.obtenerTodosLosClientes();
        
        for (Cliente c : lista) {
            // Por cada cliente, armamos un arreglo de objetos que representa una fila
            modelo.addRow(new Object[]{
                c.getCodigo(), 
                c.getNombre(), 
                c.getDireccion(), 
                c.getCorreo(), 
                c.getNumeroContacto()
            });
        }
    }
    
    // 5. Método auxiliar para optimizar el flujo de trabajo del usuario
    private void limpiarCajas() {
        textCodigo.setText("");
        textNombre.setText("");
        textDireccion.setText("");
        textCorreo.setText("");
        textNumero.setText("");
        textCodigo.requestFocus(); // Retorna el cursor a la primera caja automáticamente
    }
    */
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private java.awt.Label labelCodigo;
    private java.awt.Label labelCorreo;
    private java.awt.Label labelDireccion;
    private java.awt.Label labelNombre;
    private java.awt.Label labelNumero;
    private java.awt.TextField textCodigo;
    private java.awt.TextField textCorreo;
    private java.awt.TextField textDireccion;
    private java.awt.TextField textNombre;
    private java.awt.TextField textNumero;
    // End of variables declaration//GEN-END:variables

  


}


