/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Vista.Productos.FrmProductos;
import Gestores.GestorContactos;
import Gestores.GestorInventario;
import Gestores.GestorVentas;

/**
 *
 * @author equipo
 */
public class FrmMenu extends javax.swing.JFrame {
   private GestorContactos gestorContactos = new GestorContactos();
    private GestorInventario gestorInventario = new GestorInventario();
    private GestorVentas gestorVentas = new Gestores.GestorVentas();
            
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenu.class.getName());

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmnAreaVentas = new javax.swing.JMenu();
        jmiGestionarClientes = new javax.swing.JMenuItem();
        jmiGenerarPedido = new javax.swing.JMenuItem();
        jmiGestionarPedidos = new javax.swing.JMenuItem();
        jmiProductos = new javax.swing.JMenuItem();
        jmiProveedores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Menu");

        jmnAreaVentas.setText("Area de Ventas");

        jmiGestionarClientes.setText("Gestionar Clientes");
        jmiGestionarClientes.addActionListener(this::jmiGestionarClientesActionPerformed);
        jmnAreaVentas.add(jmiGestionarClientes);

        jmiGenerarPedido.setText("Generar Nuevo Pedido");
        jmiGenerarPedido.addActionListener(this::jmiGenerarPedidoActionPerformed);
        jmnAreaVentas.add(jmiGenerarPedido);

        jmiGestionarPedidos.setText("Gestionar Pedidos");
        jmiGestionarPedidos.addActionListener(this::jmiGestionarPedidosActionPerformed);
        jmnAreaVentas.add(jmiGestionarPedidos);

        jMenu1.add(jmnAreaVentas);

        jmiProductos.setText("Productos");
        jmiProductos.addActionListener(this::jmiProductosActionPerformed);
        jMenu1.add(jmiProductos);

        jmiProveedores.setText("Proveedores");
        jmiProveedores.addActionListener(this::jmiProveedoresActionPerformed);
        jMenu1.add(jmiProveedores);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProveedoresActionPerformed
        FrmProveedores ventanaNueva = new FrmProveedores(this.gestorContactos);
        ventanaNueva.setLocationRelativeTo(this);
        ventanaNueva.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jmiProveedoresActionPerformed

    private void jmiProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProductosActionPerformed
        FrmProductos ventanaNueva = new FrmProductos(this.gestorInventario, this.gestorContactos);
        ventanaNueva.setLocationRelativeTo(this);
        ventanaNueva.setVisible(true);
        this.setVisible(false);    
    }//GEN-LAST:event_jmiProductosActionPerformed

    private void jmiGenerarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGenerarPedidoActionPerformed
        FrmPedido ventanaPedido = new FrmPedido(this.gestorVentas, this.gestorContactos, this.gestorInventario);
        ventanaPedido.setLocationRelativeTo(this);
        ventanaPedido.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jmiGenerarPedidoActionPerformed

    private void jmiGestionarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGestionarPedidosActionPerformed
        FmrGestionPedidos ventanaGestion = new FmrGestionPedidos();
        ventanaGestion.setLocationRelativeTo(this);
        ventanaGestion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jmiGestionarPedidosActionPerformed

    private void jmiGestionarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGestionarClientesActionPerformed
        FrmClientes ventanaClientes = new FrmClientes(this.gestorContactos);
        ventanaClientes.setLocationRelativeTo(this);
        ventanaClientes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jmiGestionarClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiGenerarPedido;
    private javax.swing.JMenuItem jmiGestionarClientes;
    private javax.swing.JMenuItem jmiGestionarPedidos;
    private javax.swing.JMenuItem jmiProductos;
    private javax.swing.JMenuItem jmiProveedores;
    private javax.swing.JMenu jmnAreaVentas;
    // End of variables declaration//GEN-END:variables
}
