/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Vista.Productos.FrmProductos;
import Gestores.GestorContactos;
import Gestores.GestorInventario;
import Gestores.GestorVentas;

/**
 *
 * @author equipo
 */
public class FrmMenu extends javax.swing.JFrame {
    private GestorContactos gestorContactos = new GestorContactos();
     private GestorInventario gestorInventario= new GestorInventario();
     private GestorVentas gestorVentas = new Gestores.GestorVentas();
            
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenu.class.getName());

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAbrirAreaVentas = new javax.swing.JButton();
        btnAbrirProductos = new javax.swing.JButton();
        btnAbrirProveedores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAbrirAreaVentas.setText("Area ventas");
        btnAbrirAreaVentas.addActionListener(this::btnAbrirAreaVentasActionPerformed);

        btnAbrirProductos.setText("Productos");
        btnAbrirProductos.addActionListener(this::btnAbrirProductosActionPerformed);

        btnAbrirProveedores.setText("Proveedores");
        btnAbrirProveedores.addActionListener(this::btnAbrirProveedoresActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAbrirProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAbrirAreaVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAbrirProveedores))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(btnAbrirAreaVentas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAbrirProveedores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAbrirProductos)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirAreaVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirAreaVentasActionPerformed
        // TODO add your handling code here:
        
        FrmAreaVentas ventanaNueva = new FrmAreaVentas(this.gestorVentas, this.gestorContactos, this.gestorInventario);
        ventanaNueva.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnAbrirAreaVentasActionPerformed

    private void btnAbrirProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirProductosActionPerformed
        // TODO add your handling code here:
        FrmProductos ventanaNueva= new FrmProductos(this.gestorInventario,this.gestorContactos);
        ventanaNueva.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAbrirProductosActionPerformed

    private void btnAbrirProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirProveedoresActionPerformed
        // TODO add your handling code here:
        FrmProveedores ventanaNueva= new FrmProveedores(this.gestorContactos);
        ventanaNueva.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAbrirProveedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirAreaVentas;
    private javax.swing.JButton btnAbrirProductos;
    private javax.swing.JButton btnAbrirProveedores;
    // End of variables declaration//GEN-END:variables
}
