/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;


import Entidades.Proveedor;
import Gestores.GestorContactos;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author equipo
 */
public class FrmProveedores extends javax.swing.JFrame {
    // 1. El atributo que conectará esta ventana con la memoria global de tu sistema
    private GestorContactos gestor;
    private String rucEnEdicion = null;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmProveedores.class.getName());

    /**
     * Creates new form FrmClientes
     */
   // 2. El Constructor: Modifícalo para que exija el Gestor como parámetro
    public FrmProveedores(GestorContactos gestorCompartido) {
        initComponents(); // Método intocable autogenerado por NetBeans
        
        // Asignamos el gestor que viene desde el Menú a nuestra variable interna
        this.gestor = gestorCompartido;
        
        btnQuitarFiltro.setVisible(false);
          btnActualizar.setVisible(false);
        
        // Ejecutamos la lógica para llenar la tabla apenas la ventana nazca
        actualizarTabla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        itemEditar = new javax.swing.JMenuItem();
        textCodigo = new java.awt.TextField();
        textNombre = new java.awt.TextField();
        textDireccion = new java.awt.TextField();
        textNumero = new java.awt.TextField();
        textCorreo = new java.awt.TextField();
        labelCodigo = new java.awt.Label();
        labelNombre = new java.awt.Label();
        labelCorreo = new java.awt.Label();
        labelNumero = new java.awt.Label();
        labelDireccion = new java.awt.Label();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnBuscarPorNombre = new javax.swing.JButton();
        textBusquedaNombre = new java.awt.TextField();
        btnCancelar = new javax.swing.JButton();
        btnBuscarCodigo = new javax.swing.JButton();
        textBusquedaCodigo = new java.awt.TextField();
        jLabel1 = new javax.swing.JLabel();
        btnQuitarFiltro = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        textContacto = new java.awt.TextField();
        labelContacto = new java.awt.Label();
        btnRegresar = new javax.swing.JButton();

        itemEditar.setText("Editar");
        itemEditar.addActionListener(this::itemEditarActionPerformed);
        jPopupMenu1.add(itemEditar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proveedores");
        setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N

        textCorreo.addActionListener(this::textCorreoActionPerformed);

        labelCodigo.setText("Ingrese DNI/RUC");

        labelNombre.setText("Ingrese Nombre");

        labelCorreo.setText("Ingrese Correo");

        labelNumero.setText("Ingrese Numero");

        labelDireccion.setText("Ingrese Dirección");

        btnGuardar.setText("Registrar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI/RUC", "Nombre", "Dirección", "Contacto", "Numero", "Correo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClientes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblClientesMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);
        if (tblClientes.getColumnModel().getColumnCount() > 0) {
            tblClientes.getColumnModel().getColumn(0).setResizable(false);
            tblClientes.getColumnModel().getColumn(1).setResizable(false);
            tblClientes.getColumnModel().getColumn(2).setResizable(false);
            tblClientes.getColumnModel().getColumn(3).setResizable(false);
            tblClientes.getColumnModel().getColumn(4).setResizable(false);
            tblClientes.getColumnModel().getColumn(5).setResizable(false);
        }

        btnBuscarPorNombre.setText("Buscar por Nombre");
        btnBuscarPorNombre.addActionListener(this::btnBuscarPorNombreActionPerformed);

        textBusquedaNombre.addActionListener(this::textBusquedaNombreActionPerformed);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnBuscarCodigo.setText("Buscar por DNI/RUC");
        btnBuscarCodigo.addActionListener(this::btnBuscarCodigoActionPerformed);

        textBusquedaCodigo.addActionListener(this::textBusquedaCodigoActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Proveedores Registrados");

        btnQuitarFiltro.setText("Quitar Filtro");
        btnQuitarFiltro.addActionListener(this::btnQuitarFiltroActionPerformed);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        labelContacto.setText("Ingrese Contacto");

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(138, 138, 138))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelDireccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(labelContacto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                    .addComponent(textCorreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textNumero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textCodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textContacto, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                                .addGap(82, 82, 82))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(98, 98, 98)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(btnBuscarCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnBuscarPorNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(textBusquedaCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                            .addComponent(textBusquedaNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(69, 69, 69))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnQuitarFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(301, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textCodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textCorreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCorreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(btnRegresar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textBusquedaCodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarCodigo, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textBusquedaNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarPorNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuitarFiltro))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCorreoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            String codigo = textCodigo.getText().trim();
            
            // NUEVA LÓGICA PROACTIVA: Validación del RUC (solo 11 números)
            if (!codigo.matches("^[0-9]{11}$")) {
                JOptionPane.showMessageDialog(this, "Error: El RUC debe contener exactamente 11 números.", "Error de Formato", JOptionPane.ERROR_MESSAGE);  
                return; // Aborta la operación aquí mismo
            }

            String nombre = textNombre.getText();
            String direccion = textDireccion.getText();
            String contacto = textContacto.getText();
            String numero = textNumero.getText();
            String correo = textCorreo.getText();
            
            // B. Instanciación (Orden corregido: RUC, Nombre, Direccion, Contacto, Numero, Correo)
            Proveedor nuevoProveedor = new Proveedor(codigo, nombre, direccion, contacto, numero, correo);
            
            // C. Delegación
            gestor.registrarProveedor(nuevoProveedor);
            
            // D. Éxito (Textos corregidos)
            JOptionPane.showMessageDialog(this, "Proveedor registrado con éxito.");
            limpiarCajas();
            actualizarTabla();
        
        } catch (IllegalArgumentException ex) {
            // Intercepción de las reglas de negocio
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de Validación", JOptionPane.WARNING_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPorNombreActionPerformed
        String textoBusqueda = textBusquedaNombre.getText();
    
        if (textoBusqueda.trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe escribir una razón social para buscar.");
            return; 
        }
    
        List<Proveedor> listaResultados = gestor.buscarProveedorPorNombre(textoBusqueda);
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblClientes.getModel();
    
        if (listaResultados.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontraron proveedores con ese nombre.");
            modelo.setRowCount(0); 
        } else {
            modelo.setRowCount(0); 
            
            for (Proveedor p : listaResultados) {
                // Orden de columnas estrictamente alineado a tu diseño:
                // RUC, Nombre, Dirección, Contacto, Numero, Correo
                modelo.addRow(new Object[]{
                    p.getRuc(),
                    p.getRazonSocial(),
                    p.getDireccion(),
                    p.getContacto(),
                    p.getNumeroContacto(),
                    p.getCorreoContacto()
                });
             }
             
            btnQuitarFiltro.setVisible(true);
            textBusquedaNombre.setText("");
        }
     
        
    }//GEN-LAST:event_btnBuscarPorNombreActionPerformed

    private void textBusquedaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBusquedaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBusquedaNombreActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limpiarCajas();
        
        
        
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCodigoActionPerformed
  // 1. Recolección
        String codigoBuscado = textBusquedaCodigo.getText().trim();
        
        // 2. Validación proactiva para evitar letras sin usar try-catch
        if (!codigoBuscado.matches("^[0-9]+$")) {
             javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese únicamente números para la búsqueda.");
             return; // Detiene la ejecución
        }
    
        // 3. Búsqueda
        Proveedor proveedorEncontrado = gestor.buscarProveedorPorRuc(codigoBuscado);
    
        // 4. Renderizado visual
        if (proveedorEncontrado == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "El RUC no está registrado en el sistema.");
        } else {
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblClientes.getModel();
            modelo.setRowCount(0); 
            
            // Orden de las columnas corregido
            modelo.addRow(new Object[]{
                proveedorEncontrado.getRuc(),
                proveedorEncontrado.getRazonSocial(),
                proveedorEncontrado.getDireccion(),
                proveedorEncontrado.getContacto(),
                proveedorEncontrado.getNumeroContacto(), 
                proveedorEncontrado.getCorreoContacto()
            });
            
            btnQuitarFiltro.setVisible(true);
            textBusquedaCodigo.setText("");
        }

    }//GEN-LAST:event_btnBuscarCodigoActionPerformed

    private void textBusquedaCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBusquedaCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBusquedaCodigoActionPerformed

    private void btnQuitarFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarFiltroActionPerformed
        // TODO add your handling code here:
        actualizarTabla();
        btnQuitarFiltro.setVisible(false);
        
    }//GEN-LAST:event_btnQuitarFiltroActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
       try {
            String nombre = textNombre.getText();
            String direccion = textDireccion.getText();            
            String contacto = textContacto.getText();
            String numero = textNumero.getText();
            String correo = textCorreo.getText();
            
            // Orden corregido para que coincida con la clase Proveedor
            Proveedor proveedorModificado = new Proveedor(rucEnEdicion, nombre, direccion, contacto, numero, correo);
            
            // Mandamos al Gestor
            gestor.actualizarProveedor(proveedorModificado);
            
            // Mensaje corregido
            javax.swing.JOptionPane.showMessageDialog(this, "Proveedor actualizado correctamente.");
            
            // Limpiamos la interfaz
            limpiarCajas();
            
            // Desbloqueamos el RUC
            textCodigo.setEnabled(true);
            rucEnEdicion = "";
            
            // Regresamos los botones a la normalidad
            btnActualizar.setVisible(false);
            btnGuardar.setVisible(true);
            
            // Actualizamos la tabla
            actualizarTabla();
            
        } catch (IllegalArgumentException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void tblClientesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseReleased
        // TODO add your handling code here:
        // Verifica si fue clic derecho (Popup Trigger)
    if (evt.isPopupTrigger()) {
        // Calcula la fila en base a las coordenadas del ratón (X, Y)
        int filaSeleccionada = tblClientes.rowAtPoint(evt.getPoint());
        
        // Fuerza a la tabla a seleccionar esa fila visualmente
        if (filaSeleccionada >= 0 && filaSeleccionada < tblClientes.getRowCount()) {
            tblClientes.setRowSelectionInterval(filaSeleccionada, filaSeleccionada);
            
            // Muestra tu menú emergente (asumiendo que lo llamaste popMenuEditar)
            // en la posición exacta del ratón
            jPopupMenu1.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }
        
    }//GEN-LAST:event_tblClientesMouseReleased

    private void itemEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarActionPerformed
        // TODO add your handling code here:
        // 1. Extraemos el número de fila seleccionada
    int fila = tblClientes.getSelectedRow();
    
    if (fila != -1) { // Si hay una fila válida
        // 2. Extraemos los datos de la tabla (ajusta el orden según tus columnas reales)
        String codigo = tblClientes.getValueAt(fila, 0).toString();
        String nombre = tblClientes.getValueAt(fila, 1).toString();
        String correo = tblClientes.getValueAt(fila, 5).toString();
        String direccion = tblClientes.getValueAt(fila, 2).toString();
        String numero = tblClientes.getValueAt(fila, 4).toString();
        String contacto=tblClientes.getValueAt(fila, 3).toString();
        
        // 3. Alimentamos las cajas de texto
        textCodigo.setText(codigo);
        textNombre.setText(nombre);
        textContacto.setText(contacto);
        textDireccion.setText(direccion);
        textNumero.setText(numero);
        textCorreo.setText(correo);
        
        // 4. Guardamos el DNI en la memoria global y bloqueamos la caja para que no lo cambien
        rucEnEdicion = codigo;
        textCodigo.setEnabled(false);
        
        // 5. Cambio de estado visual (asumiendo que creaste btnActualizar)
        btnGuardar.setVisible(false);
        btnActualizar.setVisible(true);
    }
    }//GEN-LAST:event_itemEditarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        FrmMenu ventanaMenu=new FrmMenu();
        ventanaMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed
      // 4. Lógica de Lectura Visual (El puente entre la lista y la pantalla)
    private void actualizarTabla() {
        // Capturamos el modelo estructural de la tabla (tblClientes)
        DefaultTableModel modelo = (DefaultTableModel) tblClientes.getModel();
       
        
        // Reiniciamos las filas a cero para no duplicar los datos visualmente al recargar
        modelo.setRowCount(0);
        
        // Extraemos la memoria temporal y la recorremos
        List<Proveedor> lista = gestor.obtenerTodosLosProveedores();
        
        for (Proveedor c : lista) {
            // Por cada cliente, armamos un arreglo de objetos que representa una fila
            modelo.addRow(new Object[]{
                c.getRuc(), 
                c.getRazonSocial(),
                c.getDireccion(),
                c.getContacto(),
                c.getNumeroContacto(),
                c.getCorreoContacto(),
                  
            });
        }
        ajustarAnchoColumnas();
    }
    
    // 5. Método auxiliar para optimizar el flujo de trabajo del usuario
    private void limpiarCajas() {
        textCodigo.setText("");
        textNombre.setText("");
        textContacto.setText("");
        textNumero.setText("");
        textDireccion.setText("");
        textCorreo.setText("");
        textCodigo.requestFocus(); // Retorna el cursor a la primera caja automáticamente
    }
    private void ajustarAnchoColumnas() {
    // 1. Extraemos el modelo estructural de las columnas de tu tabla
    javax.swing.table.TableColumnModel modeloColumna = tblClientes.getColumnModel();

    // 2. Recorremos cada una de las columnas
    for (int i = 0; i < modeloColumna.getColumnCount(); i++) {
        int anchoCalculado = 50; // Un ancho mínimo por seguridad

        // A. Revisamos cuánto espacio exige el texto del título de la columna
        javax.swing.table.TableColumn columna = modeloColumna.getColumn(i);
        javax.swing.table.TableCellRenderer rendererCabecera = columna.getHeaderRenderer();
        
        if (rendererCabecera == null) {
            rendererCabecera = tblClientes.getTableHeader().getDefaultRenderer();
        }
        
        java.awt.Component compCabecera = rendererCabecera.getTableCellRendererComponent(
            tblClientes, columna.getHeaderValue(), false, false, 0, i);
        
        anchoCalculado = Math.max(anchoCalculado, compCabecera.getPreferredSize().width);

        // B. Recorremos todas las filas de esa columna para buscar el texto más largo
        for (int j = 0; j < tblClientes.getRowCount(); j++) {
            javax.swing.table.TableCellRenderer rendererCelda = tblClientes.getCellRenderer(j, i);
            java.awt.Component compCelda = rendererCelda.getTableCellRendererComponent(
                tblClientes, tblClientes.getValueAt(j, i), false, false, j, i);
            
            anchoCalculado = Math.max(anchoCalculado, compCelda.getPreferredSize().width);
        }

        // C. Le aplicamos el tamaño ganador a la columna, más 10 píxeles de margen estético
        columna.setPreferredWidth(anchoCalculado + 10);
    }
}
    
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscarCodigo;
    private javax.swing.JButton btnBuscarPorNombre;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnQuitarFiltro;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JMenuItem itemEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label labelCodigo;
    private java.awt.Label labelContacto;
    private java.awt.Label labelCorreo;
    private java.awt.Label labelDireccion;
    private java.awt.Label labelNombre;
    private java.awt.Label labelNumero;
    private javax.swing.JTable tblClientes;
    private java.awt.TextField textBusquedaCodigo;
    private java.awt.TextField textBusquedaNombre;
    private java.awt.TextField textCodigo;
    private java.awt.TextField textContacto;
    private java.awt.TextField textCorreo;
    private java.awt.TextField textDireccion;
    private java.awt.TextField textNombre;
    private java.awt.TextField textNumero;
    // End of variables declaration//GEN-END:variables

  


}


