/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Entidades.Cliente;
import Entidades.DetallePedido;
import Entidades.Producto;
import Gestores.GestorContactos;
import Gestores.GestorInventario;
import Gestores.GestorVentas;
import Vista.Productos.jdialBuscarProducto;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author equipo
 */
public class FrmPedido extends javax.swing.JFrame {
    // Los 3 gestores necesarios
    private GestorVentas gestorVentas;
    private GestorContactos gestorContactos;
    private GestorInventario gestorInventario;
    
    // Cesta temporal de ventas
    private List<DetallePedido> carritoTemporal;
    
    // Variables temporales capturadas por las lupas
    private Producto productoSeleccionadoTemporal = null;
    private Cliente clienteSeleccionadoTemporal = null;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPedido.class.getName());

    /**
     * Creates new form FrmPedido
     */
   // Constructor adaptado
    public FrmPedido(GestorVentas gVentas, GestorContactos gContactos, GestorInventario gInv) {
        initComponents();
        this.gestorVentas = gVentas;
        this.gestorContactos = gContactos;
        this.gestorInventario = gInv;
        this.carritoTemporal = new ArrayList<>();
        
        // Bloqueo de cajas
        txtProductoSeleccionado.setEditable(false);
        txtClienteSeleccionado.setEditable(false);
        
        this.setTitle("Generar Nuevo Pedido (Venta)");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnBuscarProducto = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnBuscarCliente = new javax.swing.JButton();
        txtProductoSeleccionado = new javax.swing.JTextField();
        txtClienteSeleccionado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        txtPrecioVenta = new javax.swing.JTextField();
        btnAgregarAlCarrito = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        btnProcesarCompra = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Producto");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Descripcion", "Cantidad", "Precio", "Sub Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnBuscarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search.png"))); // NOI18N
        btnBuscarProducto.addActionListener(this::btnBuscarProductoActionPerformed);

        jLabel4.setText("Cliente");

        btnBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search.png"))); // NOI18N
        btnBuscarCliente.addActionListener(this::btnBuscarClienteActionPerformed);

        jLabel1.setText("Cantidad");

        jLabel2.setText("Precio Venta");

        btnAgregarAlCarrito.setText("Agregar");
        btnAgregarAlCarrito.addActionListener(this::btnAgregarAlCarritoActionPerformed);

        jLabel5.setText("Estado");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solicitada", "Pendiente", "Procesada", "Abonada" }));

        btnProcesarCompra.setText("Procesar Compra");
        btnProcesarCompra.addActionListener(this::btnProcesarCompraActionPerformed);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegresar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProcesarCompra))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                .addComponent(btnBuscarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtProductoSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtClienteSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAgregarAlCarrito))))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnRegresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtProductoSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1)
                                        .addComponent(txtCantidad))
                                    .addComponent(btnBuscarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBuscarCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtClienteSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2)
                                        .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregarAlCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProcesarCompra))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        // TODO add your handling code here:
        // Abrimos el buscador pasándole el gestor
        jdialBuscarProducto buscador = new jdialBuscarProducto(null, true, gestorInventario);
        buscador.setLocationRelativeTo(this);
        buscador.setVisible(true); // El código se pausa aquí hasta que la ventana se cierre

        // Cuando se cierra, le pedimos a la ventana qué producto eligió el usuario
        Entidades.Producto prodEncontrado = buscador.getProductoSeleccionado();

        if (prodEncontrado != null) {
            this.productoSeleccionadoTemporal = prodEncontrado;
            // Mostramos el nombre en la caja de texto visual (txtProductoSeleccionado)
            txtProductoSeleccionado.setText(prodEncontrado.getDescripcion());
            if (prodEncontrado.getPrecioVentaBase() != null) {
                txtPrecioVenta.setText(String.valueOf(prodEncontrado.getPrecioVentaBase()));
            }
        }
        
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:
        jdialBuscarCliente buscador = new jdialBuscarCliente(this, true, gestorContactos);
        buscador.setLocationRelativeTo(this);
        buscador.setVisible(true);

        Entidades.Cliente cliEncontrado = buscador.getClienteSeleccionado();
        
        if (cliEncontrado != null) {
            this.clienteSeleccionadoTemporal = cliEncontrado;
            txtClienteSeleccionado.setText(cliEncontrado.getNombre());
        }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnAgregarAlCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAlCarritoActionPerformed
        try {
            if (productoSeleccionadoTemporal == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un producto.");
                return;
            }
            if (clienteSeleccionadoTemporal == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un cliente.");
                return;
            }

            String textoCantidad = txtCantidad.getText().trim();
            String textoPrecio = txtPrecioVenta.getText().trim().replace(",", ".");

            int cantidad = Integer.parseInt(textoCantidad);
            double precioVenta = Double.parseDouble(textoPrecio);

            // Validamos stock disponible antes de vender
            if (productoSeleccionadoTemporal.getStock() < cantidad) {
                javax.swing.JOptionPane.showMessageDialog(this, "Stock insuficiente. Disponible: " + productoSeleccionadoTemporal.getStock(), "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Creamos el Detalle de Pedido (Venta)
            Entidades.DetallePedido nuevoDetalle = new Entidades.DetallePedido(cantidad, precioVenta, productoSeleccionadoTemporal);
            carritoTemporal.add(nuevoDetalle);
            
            actualizarTablaCarrito();

            // Bloqueamos el cliente para que no lo cambien a mitad de la factura
            btnBuscarCliente.setEnabled(false); // Tu botón de lupa de cliente

            // Limpiamos cajas de producto
            productoSeleccionadoTemporal = null;
            txtProductoSeleccionado.setText("");
            txtCantidad.setText("");
            txtPrecioVenta.setText("");

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Verifique los datos ingresados: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarAlCarritoActionPerformed

    private void btnProcesarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarCompraActionPerformed
        if (carritoTemporal.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "El carrito de ventas está vacío.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // 1. Validamos que exista un CLIENTE (No un proveedor)
            if(this.clienteSeleccionadoTemporal == null){
                javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente válido.");
                return;
            }

            String estadoSeleccionado = cmbEstado.getSelectedItem().toString();
            String fechaActual = java.time.LocalDate.now().toString();
            
            // 2. Creamos el PEDIDO DE VENTA
            Entidades.Pedido nuevoPedido = new Entidades.Pedido(fechaActual, fechaActual, estadoSeleccionado, "Contado", fechaActual, 0.0, this.clienteSeleccionadoTemporal);

            for (Entidades.DetallePedido detalle : carritoTemporal) {
                nuevoPedido.agregarDetalleVenta(detalle);
                
                // 3. Regla de Negocio: Si la venta se marca como "Entregado", descontamos el stock físico
                if (estadoSeleccionado.equals("Entregado")) {
                    detalle.getProducto().actualizarStock(detalle.getCantidadVendida(), "salida");
                }
            }
            
            // 4. Registramos en el cliente y en el historial global de ventas
            this.clienteSeleccionadoTemporal.getPedidos().add(nuevoPedido);
            gestorVentas.registrarPedido(nuevoPedido);

            javax.swing.JOptionPane.showMessageDialog(this, "¡Pedido de venta registrado con éxito!");
            this.dispose();

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al procesar: " + ex.getMessage(), "Error Crítico", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnProcesarCompraActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        // Buscamos el Área de Ventas original (que tiene los gestores vivos) y lo encendemos
        for (java.awt.Window window : java.awt.Window.getWindows()) {
            if (window instanceof FrmAreaVentas) {
                window.setVisible(true);
                break;
            }
        }
        
        // Cerramos la ventana actual (la del pedido)
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed
      private void actualizarTablaCarrito() {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0); 

        for (Entidades.DetallePedido detalle : carritoTemporal) {
            double subtotal = detalle.getCantidadVendida() * detalle.getPrecioVentaCongelado();
            
            modelo.addRow(new Object[]{
                detalle.getProducto().getId(),                             
                detalle.getProducto().getDescripcion(),                    
                detalle.getCantidadVendida(),                            
                String.format("S/ %.2f", detalle.getPrecioVentaCongelado()), 
                String.format("S/ %.2f", subtotal)                      
            });
        }
    }
    
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAlCarrito;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnProcesarCompra;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtClienteSeleccionado;
    private javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextField txtProductoSeleccionado;
    // End of variables declaration//GEN-END:variables
}
