/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Entidades.Cliente;
import Entidades.DetallePedido;
import Entidades.Producto;
import Gestores.GestorContactos;
import Gestores.GestorInventario;
import Gestores.GestorVentas;
import Vista.Productos.jdialBuscarProducto;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author equipo
 */
public class FrmPedido extends javax.swing.JFrame {
    // Los 3 gestores necesarios
    private GestorVentas gestorVentas;
    private GestorContactos gestorContactos;
    private GestorInventario gestorInventario;
    
    // Cesta temporal de ventas
    private List<DetallePedido> carritoTemporal;
    
    // Variables temporales capturadas por las lupas
    private Producto productoSeleccionadoTemporal = null;
    private Cliente clienteSeleccionadoTemporal = null;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPedido.class.getName());

    /**
     * Creates new form FrmPedido
     */
   // Constructor adaptado
    public FrmPedido(Gestores.GestorVentas gVentas, Gestores.GestorContactos gContactos, Gestores.GestorInventario gInv) {
        initComponents();
        this.gestorVentas = gVentas;
        this.gestorContactos = gContactos;
        this.gestorInventario = gInv;
        this.carritoTemporal = new java.util.ArrayList<>();
        
        // Bloqueo de cajas
        txtProductoSeleccionado.setEditable(false);
        txtClienteSeleccionado.setEditable(false);
        
        // CORRECCIÓN: Se actualiza el ComboBox programáticamente para evitar tocar el código bloqueado de NetBeans
        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "Entregado" }));
        
        this.setTitle("Generar Nuevo Pedido (Venta)");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnBuscarProducto = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnBuscarCliente = new javax.swing.JButton();
        txtProductoSeleccionado = new javax.swing.JTextField();
        txtClienteSeleccionado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        txtPrecioVenta = new javax.swing.JTextField();
        btnAgregarAlCarrito = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        btnProcesarCompra = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbTipoVenta = new javax.swing.JComboBox<>();
        jdFechaRecepcion = new com.toedter.calendar.JDateChooser();
        jdFechaLimitePago = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Producto");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Descripcion", "Cantidad", "Precio", "Sub Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnBuscarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search.png"))); // NOI18N
        btnBuscarProducto.addActionListener(this::btnBuscarProductoActionPerformed);

        jLabel4.setText("Cliente");

        btnBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search.png"))); // NOI18N
        btnBuscarCliente.addActionListener(this::btnBuscarClienteActionPerformed);

        jLabel1.setText("Cantidad");

        jLabel2.setText("Precio Venta");

        btnAgregarAlCarrito.setText("Agregar");
        btnAgregarAlCarrito.addActionListener(this::btnAgregarAlCarritoActionPerformed);

        jLabel5.setText("Estado");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Pendiente", "Entregado", "Cancelado" }));

        btnProcesarCompra.setText("Procesar Compra");
        btnProcesarCompra.addActionListener(this::btnProcesarCompraActionPerformed);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        jLabel6.setText("Fecha de Entrega");

        jLabel7.setText("Fecha Limite de pago");

        jLabel8.setText("Tipo de Venta");

        cmbTipoVenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contado", "Credito" }));
        cmbTipoVenta.addActionListener(this::cmbTipoVentaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegresar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cmbTipoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(btnProcesarCompra))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                        .addComponent(btnBuscarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jLabel6))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtProductoSeleccionado, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                .addComponent(txtClienteSeleccionado, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                .addComponent(jdFechaRecepcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAgregarAlCarrito))
                                .addComponent(jdFechaLimitePago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnRegresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtProductoSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addComponent(txtCantidad))
                            .addComponent(btnBuscarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtClienteSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnBuscarCliente))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btnAgregarAlCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jdFechaLimitePago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jdFechaRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProcesarCompra)
                    .addComponent(jLabel8)
                    .addComponent(cmbTipoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        // TODO add your handling code here:
        // Abrimos el buscador pasándole el gestor
        jdialBuscarProducto buscador = new jdialBuscarProducto(null, true, gestorInventario);
        buscador.setLocationRelativeTo(this);
        buscador.setVisible(true); // El código se pausa aquí hasta que la ventana se cierre

        // Cuando se cierra, le pedimos a la ventana qué producto eligió el usuario
        Entidades.Producto prodEncontrado = buscador.getProductoSeleccionado();

        if (prodEncontrado != null) {
            this.productoSeleccionadoTemporal = prodEncontrado;
            // Mostramos el nombre en la caja de texto visual (txtProductoSeleccionado)
            txtProductoSeleccionado.setText(prodEncontrado.getDescripcion());
            if (prodEncontrado.getPrecioVentaBase() != null) {
                txtPrecioVenta.setText(String.valueOf(prodEncontrado.getPrecioVentaBase()));
            }
        }
        
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:
        jdialBuscarCliente buscador = new jdialBuscarCliente(this, true, gestorContactos);
        buscador.setLocationRelativeTo(this);
        buscador.setVisible(true);

        Entidades.Cliente cliEncontrado = buscador.getClienteSeleccionado();
        
        if (cliEncontrado != null) {
            this.clienteSeleccionadoTemporal = cliEncontrado;
            txtClienteSeleccionado.setText(cliEncontrado.getNombre());
        }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnAgregarAlCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAlCarritoActionPerformed
        try {
        if (productoSeleccionadoTemporal == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un producto.");
            return;
        }
        if (clienteSeleccionadoTemporal == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un cliente.");
            return;
        }

        int cantidad = Integer.parseInt(txtCantidad.getText().trim());
        double precioVenta = Double.parseDouble(txtPrecioVenta.getText().trim().replace(",", "."));

        if (productoSeleccionadoTemporal.getStock() < cantidad) {
            javax.swing.JOptionPane.showMessageDialog(this, "Stock insuficiente.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        Entidades.DetallePedido nuevoDetalle = new Entidades.DetallePedido(cantidad, precioVenta, productoSeleccionadoTemporal);
        carritoTemporal.add(nuevoDetalle);
        actualizarTablaCarrito();

        if (!carritoTemporal.isEmpty()) {
            jdFechaRecepcion.setEnabled(false);
            jdFechaLimitePago.setEnabled(false);
            btnBuscarCliente.setEnabled(false);
            cmbTipoVenta.setEnabled(false);
        }

        productoSeleccionadoTemporal = null;
        txtProductoSeleccionado.setText("");
        txtCantidad.setText("");
        txtPrecioVenta.setText("");

    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Verifique los datos: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnAgregarAlCarritoActionPerformed

    private void btnProcesarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarCompraActionPerformed
        
        if (carritoTemporal.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "El carrito de ventas está vacío.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
        

    try {
        if (this.clienteSeleccionadoTemporal == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente válido.");
            return;
        }

        String estadoSeleccionado = cmbEstado.getSelectedItem().toString();
        String tipoVenta = cmbTipoVenta.getSelectedItem().toString();
        String fechaEmision = java.time.LocalDate.now().toString();
        
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        String fechaRecepcion = "";
        
        if (jdFechaRecepcion.getDate() != null) {
            fechaRecepcion = sdf.format(jdFechaRecepcion.getDate());
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione una fecha de entrega en el calendario.");
            return;
        }

        String fechaLimitePago = "";
        if (tipoVenta.equals("Credito")) {
            if (jdFechaLimitePago.getDate() != null) {
                fechaLimitePago = sdf.format(jdFechaLimitePago.getDate());
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha límite de pago.");
                return;
            }
        } else {
            fechaLimitePago = fechaEmision;
        }

        double deudaInicial = 0.0;
        if (tipoVenta.equals("Credito")) {
            for (Entidades.DetallePedido detalle : carritoTemporal) {
                deudaInicial += (detalle.getCantidadVendida() * detalle.getPrecioVentaCongelado());
            }
        }

        Entidades.Pedido nuevoPedido = new Entidades.Pedido(
            fechaEmision, 
            fechaRecepcion, 
            estadoSeleccionado, 
            tipoVenta, 
            fechaLimitePago, 
            deudaInicial, 
            this.clienteSeleccionadoTemporal
        );
        
        nuevoPedido.getDetalles().addAll(carritoTemporal);

        this.clienteSeleccionadoTemporal.getPedidos().add(nuevoPedido);
        gestorVentas.registrarVenta(nuevoPedido);
        
        javax.swing.JOptionPane.showMessageDialog(this, "¡Venta registrada con éxito!");
        this.dispose(); 

    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al procesar: " + ex.getMessage(), "Error Crítico", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnProcesarCompraActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
       // Buscamos el Menú principal en la memoria de Java y lo volvemos a encender
    for (java.awt.Window window : java.awt.Window.getWindows()) {
        if (window instanceof Vista.FrmMenu) {
            window.setVisible(true);
            break;
        }
    }
    
    // Cerramos y destruimos la ventana actual en la que estamos
    this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void cmbTipoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoVentaActionPerformed
      String tipo = cmbTipoVenta.getSelectedItem().toString();
    
    if (tipo.equals("Contado")) {
        // Bloqueamos el calendario y autocompletamos con la fecha actual
        jdFechaLimitePago.setEnabled(false);
        jdFechaLimitePago.setDate(new java.util.Date()); 
    } else {
        // Si es crédito, liberamos el calendario y lo dejamos en blanco para que el usuario elija
        jdFechaLimitePago.setEnabled(true);
        jdFechaLimitePago.setDate(null); 
    }
    }//GEN-LAST:event_cmbTipoVentaActionPerformed
      private void actualizarTablaCarrito() {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0); 

        for (Entidades.DetallePedido detalle : carritoTemporal) {
            double subtotal = detalle.getCantidadVendida() * detalle.getPrecioVentaCongelado();
            
            modelo.addRow(new Object[]{
                detalle.getProducto().getId(),                             
                detalle.getProducto().getDescripcion(),                    
                detalle.getCantidadVendida(),                            
                String.format("S/ %.2f", detalle.getPrecioVentaCongelado()), 
                String.format("S/ %.2f", subtotal)                      
            });
        }
    }
    
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAlCarrito;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnProcesarCompra;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbTipoVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JDateChooser jdFechaLimitePago;
    private com.toedter.calendar.JDateChooser jdFechaRecepcion;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtClienteSeleccionado;
    private javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextField txtProductoSeleccionado;
    // End of variables declaration//GEN-END:variables
}
