/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Entidades.Pedido;
import Gestores.GestorVentas;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author equipo
 */
public class FrmReporteDeudores extends javax.swing.JFrame {
    
    private GestorVentas gestorVentas;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmReporteDeudores.class.getName());

    /**
     * Creates new form FrmReporteDeudores
     */
    public FrmReporteDeudores(GestorVentas gestor) {
        initComponents();
        this.gestorVentas = gestor;
        this.setTitle("Reporte de Cuentas por Cobrar");
        cargarDeudores();
    }
    // Método que filtra y ordena a los que deben dinero
    private void cargarDeudores() {
        DefaultTableModel modelo = (DefaultTableModel) tblDeudores.getModel();
        modelo.setRowCount(0);

        // Pedimos todos los pedidos, filtramos solo los que deben > 0 y los ordenamos por fecha
        List<Pedido> deudores = gestorVentas.obtenerHistorialPedidos().stream()
                .filter(p -> p.getDeudaPendiente() > 0)
                .sorted((p1, p2) -> p1.getFechaLimitePago().compareTo(p2.getFechaLimitePago()))
                .collect(Collectors.toList());

        for (Pedido p : deudores) {
             modelo.addRow(new Object[]{
                p.getCodigo(),
                p.getCliente().getNombre(),
                p.getCliente().getNumeroContacto(),
                p.getFechaEmision(),             // <- AGREGADO (Para la columna "Fecha")
                p.getFechaLimitePago(),          // (Para la columna "Límite")
                String.format("S/ %.2f", p.getDeudaPendiente()) // (Para la columna "Deuda")
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDeudores = new javax.swing.JTable();
        btnCobrar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblDeudores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "N° Pedido", "Cliente", "Teléfono", "Fecha", "Límite", "Deuda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDeudores);
        if (tblDeudores.getColumnModel().getColumnCount() > 0) {
            tblDeudores.getColumnModel().getColumn(0).setResizable(false);
            tblDeudores.getColumnModel().getColumn(1).setResizable(false);
            tblDeudores.getColumnModel().getColumn(2).setResizable(false);
            tblDeudores.getColumnModel().getColumn(3).setResizable(false);
            tblDeudores.getColumnModel().getColumn(4).setResizable(false);
            tblDeudores.getColumnModel().getColumn(5).setResizable(false);
        }

        btnCobrar.setText("Cobrar");
        btnCobrar.addActionListener(this::btnCobrarActionPerformed);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnRegresar)
                        .addGap(143, 143, 143)
                        .addComponent(btnCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCobrar)
                    .addComponent(btnRegresar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarActionPerformed
        int fila = tblDeudores.getSelectedRow();
        if (fila != -1) {
            try {
                // Sacamos el ID del pedido de la primera columna
                int codigo = Integer.parseInt(tblDeudores.getValueAt(fila, 0).toString());
                Pedido pedidoDeudor = gestorVentas.obtenerDetallesDePedido(codigo);

                if (pedidoDeudor != null) {
                    // Reutilizamos tu ventana de caja existente
                    jdialProcesarVenta caja = new jdialProcesarVenta(this, true);
                    caja.prepararCobro(pedidoDeudor, gestorVentas);
                    caja.setLocationRelativeTo(this);
                    
                    // Se pausa aquí hasta cobrar
                    caja.setVisible(true);
                    
                    // Al cerrar la caja, la tabla se actualiza sola (desaparece si pagó todo)
                    cargarDeudores();
                }
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un deudor de la lista primero.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnCobrarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
      
        for (java.awt.Window window : java.awt.Window.getWindows()) {
            if (window instanceof Vista.FrmMenu) {
                window.setVisible(true);
                break; 
            }
        }
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCobrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDeudores;
    // End of variables declaration//GEN-END:variables
}
