/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;


/**
 *
 * @author equipo
 */
public class jdialProcesarVenta extends javax.swing.JDialog {
    private Entidades.Pedido pedidoActivo;
    private Gestores.GestorVentas gestor;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jdialProcesarVenta.class.getName());
    
    /**
     * Creates new form jdialProcesarVenta
     */
    public jdialProcesarVenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public void prepararCobro(Entidades.Pedido pedido, Gestores.GestorVentas gestorActivo) {
      this.pedidoActivo = pedido;
        this.gestor = gestorActivo;

        // Llenamos la pantalla con los datos estáticos del pedido
        lblCodigo.setText("Pedido #" + pedido.getCodigo());
        lblCliente.setText("Cliente: " + pedido.getCliente().getNombre());
        lblDeuda.setText(String.format("Deuda Total: S/ %.2f", pedido.getDeudaPendiente()));
        
        // Estado inicial de la caja
        txtAbono.setText("");
        lblVuelto.setText("Ingrese el monto recibido...");
        lblVuelto.setForeground(java.awt.Color.BLACK); // Color neutral por defecto
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCodigo = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblDeuda = new javax.swing.JLabel();
        lblVuelto = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        txtAbono = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblCodigo.setText("Codigo");

        lblCliente.setText("Cliente");

        lblDeuda.setText("Deuda");

        lblVuelto.setText("Vuelto");

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(this::btnConfirmarActionPerformed);

        txtAbono.addActionListener(this::txtAbonoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVuelto)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCodigo)
                        .addGap(18, 18, 18)
                        .addComponent(lblCliente)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnConfirmar))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                                .addComponent(txtAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(71, 71, 71))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblDeuda)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(lblCliente)
                    .addComponent(lblDeuda))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVuelto)
                    .addComponent(txtAbono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnConfirmar)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        try {
            String texto = txtAbono.getText().replace(",", ".");
            double abono = texto.isEmpty() ? 0.0 : Double.parseDouble(texto);

            if (abono <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un monto mayor a cero.");
                return;
            }

            // 1. Creamos la entidad del pago en Java PRIMERO
            String fechaHoy = java.time.LocalDate.now().toString();
            Entidades.PagoAbono nuevoPago = new Entidades.PagoAbono(fechaHoy, abono, pedidoActivo);
            
            // 2. Se lo enviamos al gestor para que actualice la deuda Y guarde el insert en PagoAbono
            gestor.registrarPagoAbono(nuevoPago);

            // 3. Generamos el texto del recibo (que ahora ya tendrá el código real de SQL)
            String textoComprobante = nuevoPago.procesarPago(); 

            // 4. Abrimos el comprobante visual
            jdialRecibo ventanaRecibo = new jdialRecibo(null, true);
            ventanaRecibo.mostrarRecibo(textoComprobante);
            ventanaRecibo.setLocationRelativeTo(this);
            
            ventanaRecibo.setVisible(true); 

            javax.swing.JOptionPane.showMessageDialog(this, "Pago finalizado exitosamente.");
            this.dispose(); 

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void txtAbonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAbonoActionPerformed
        try {
            // Reemplazamos coma por punto por si el usuario se equivoca al teclear
            String texto = txtAbono.getText().replace(",", ".");
            
            // Si está vacío, asumimos 0
            double abono = texto.isEmpty() ? 0.0 : Double.parseDouble(texto);
            double deuda = pedidoActivo.getDeudaPendiente();
            double diferencia = abono - deuda;

            if (diferencia >= 0) {
                // El cliente dio de más o exacto (Hay vuelto)
                lblVuelto.setText(String.format("%.2f", diferencia));
                
            } else {
                // El cliente dio de menos (Queda deuda pendiente)
                lblVuelto.setText("0.00");
               
            }
        } catch (NumberFormatException e) {
            // Si escribe letras, reseteamos a 0
            lblVuelto.setText("0.00");
            
        }
    }//GEN-LAST:event_txtAbonoActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDeuda;
    private javax.swing.JLabel lblVuelto;
    private javax.swing.JTextField txtAbono;
    // End of variables declaration//GEN-END:variables
}
