/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Entidades.Proveedor;
import Gestores.GestorContactos;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author equipo
 */
public class jdialBuscarProveedor extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jdialBuscarProveedor.class.getName());
    // 1. Añadimos el gestor correspondiente y la variable mensajera
    private GestorContactos gestor;
    private Proveedor proveedorSeleccionado = null;

    /**
     * Creates new form jdialBuscarProveedor
     */
    public jdialBuscarProveedor(java.awt.Frame parent, boolean modal, GestorContactos gestorContactos) {
        super(parent, modal);
        initComponents();
        this.gestor = gestorContactos;
        
        // Llenamos la tabla al abrir la ventana usando una búsqueda vacía
        btnBuscarActionPerformed(null);
    }
    public Proveedor getProveedorSeleccionado() {
        return this.proveedorSeleccionado;}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarProveedor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProveedores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        jLabel1.setText("Buscar Proveedor");

        tblProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI/RUC", "Nombre", "Dirección", "Contacto", "Numero", "Correo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProveedores.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProveedoresMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblProveedoresMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblProveedores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(btnBuscar)))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String textoBusqueda = txtBuscarProveedor.getText().trim();
        List<Proveedor> listaResultados;
        
        // Decidimos qué lista mostrar según la caja de texto
        if (textoBusqueda.isEmpty()) {
            listaResultados = gestor.obtenerTodosLosProveedores();
        } else {
            listaResultados = gestor.buscarProveedorPorNombre(textoBusqueda);
        }
        
        DefaultTableModel modelo = (DefaultTableModel) tblProveedores.getModel();
        modelo.setRowCount(0); // Limpiamos
        
        // Llenamos la tabla
        for (Proveedor p : listaResultados) {
            modelo.addRow(new Object[]{
                p.getRuc(), 
                p.getRazonSocial(), 
                p.getDireccion(), 
                p.getContacto(), 
                p.getNumeroContacto(), 
                p.getCorreoContacto()
            });
        }
        ajustarAnchoColumnas();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblProveedoresMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProveedoresMouseReleased
       
    }//GEN-LAST:event_tblProveedoresMouseReleased

    private void tblProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProveedoresMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) { // ¿Fueron dos clics seguidos?
            int fila = tblProveedores.getSelectedRow();
            
            if (fila != -1) {
                // Extraemos el RUC de la primera columna (columna 0)
                String ruc = tblProveedores.getValueAt(fila, 0).toString();
                
                // Usamos el gestor de contactos para encontrar al objeto real
                this.proveedorSeleccionado = gestor.buscarProveedorPorRuc(ruc);
                
                // Cerramos la ventana para devolver la información
                this.dispose(); 
            }
        }
    }//GEN-LAST:event_tblProveedoresMouseClicked
    // Método estético auxiliar
    private void ajustarAnchoColumnas() {
        javax.swing.table.TableColumnModel modeloColumna = tblProveedores.getColumnModel();
        for (int i = 0; i < modeloColumna.getColumnCount(); i++) {
            int anchoCalculado = 50; 
            javax.swing.table.TableColumn columna = modeloColumna.getColumn(i);
            javax.swing.table.TableCellRenderer rendererCabecera = columna.getHeaderRenderer();
            if (rendererCabecera == null) rendererCabecera = tblProveedores.getTableHeader().getDefaultRenderer();
            java.awt.Component compCabecera = rendererCabecera.getTableCellRendererComponent(tblProveedores, columna.getHeaderValue(), false, false, 0, i);
            anchoCalculado = Math.max(anchoCalculado, compCabecera.getPreferredSize().width);
            for (int j = 0; j < tblProveedores.getRowCount(); j++) {
                javax.swing.table.TableCellRenderer rendererCelda = tblProveedores.getCellRenderer(j, i);
                java.awt.Component compCelda = rendererCelda.getTableCellRendererComponent(tblProveedores, tblProveedores.getValueAt(j, i), false, false, j, i);
                anchoCalculado = Math.max(anchoCalculado, compCelda.getPreferredSize().width);
            }
            columna.setPreferredWidth(anchoCalculado + 10);
        }
    }
    /**
     * @param args the command line arguments
     */
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProveedores;
    private javax.swing.JTextField txtBuscarProveedor;
    // End of variables declaration//GEN-END:variables
}
