/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import Gestores.GestorInventario;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author equipo
 */
public class jdialKardex extends javax.swing.JDialog {
    private GestorInventario gestor;
    private int idProducto;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jdialKardex.class.getName());

    /**
     * Creates new form jdialKardex
     */
    public jdialKardex(java.awt.Frame parent, boolean modal,int idProducto, String nombreProducto, GestorInventario gestor) {
        super(parent, modal);
        initComponents();
        this.idProducto = idProducto;
        this.gestor = gestor;
        
        // Le ponemos un título bonito a la ventana
        this.setTitle("Tarjeta de Almacén: " + nombreProducto);
        
        // Llenamos la tabla
        cargarHistorialKardex();
    }
    
    private void cargarHistorialKardex() {
        // Asumiendo que dibujaste una tabla llamada tblKardex en este JDialog
        DefaultTableModel modelo = (DefaultTableModel) tblKardex.getModel();
        modelo.setRowCount(0);
        
        // Le pedimos al gestor la bitácora SOLO de este producto
        List<Entidades.MovimientosKardex> historial = gestor.obtenerKardexPorProducto(this.idProducto);
        
        // Llenamos la tabla fila por fila
       for (Entidades.MovimientosKardex mov : historial) {
        // La vista ya no calcula nada matemático, solo pide los datos y los formatea a texto (S/.)
             modelo.addRow(new Object[]{
             mov.getIdMovimiento(),
             mov.getFechaMovimiento(),
             mov.getTipoMovimiento().toUpperCase(),
             mov.getCantidadFisica(),
             String.format("S/ %.2f", mov.getValorUnitario()),
             String.format("S/ %.2f", mov.getTotalMovimiento()), // El objeto hace el cálculo
             mov.getSaldoCantidadActual(),
             String.format("S/ %.2f", mov.getSaldoCostoPromedio()),
             String.format("S/ %.2f", mov.getValorTotalSaldo())   // El objeto hace el cálculo
             });
        }
    }
    private void ajustarAnchoColumnas() {
        // 1. Extraemos el modelo estructural de las columnas de tu tabla
        javax.swing.table.TableColumnModel modeloColumna = tblKardex.getColumnModel();

         // 2. Recorremos cada una de las columnas
        for (int i = 0; i < modeloColumna.getColumnCount(); i++) {
             int anchoCalculado = 50; // Un ancho mínimo por seguridad

             // A. Revisamos cuánto espacio exige el texto del título de la columna
             javax.swing.table.TableColumn columna = modeloColumna.getColumn(i);
             javax.swing.table.TableCellRenderer rendererCabecera = columna.getHeaderRenderer();
        
            if (rendererCabecera == null) {
                 rendererCabecera = tblKardex.getTableHeader().getDefaultRenderer();
                }
        
            java.awt.Component compCabecera = rendererCabecera.getTableCellRendererComponent(
            tblKardex, columna.getHeaderValue(), false, false, 0, i);
        
            anchoCalculado = Math.max(anchoCalculado, compCabecera.getPreferredSize().width);

            // B. Recorremos todas las filas de esa columna para buscar el texto más largo
            for (int j = 0; j < tblKardex.getRowCount(); j++) {
                javax.swing.table.TableCellRenderer rendererCelda = tblKardex.getCellRenderer(j, i);
                java.awt.Component compCelda = rendererCelda.getTableCellRendererComponent(
                tblKardex, tblKardex.getValueAt(j, i), false, false, j, i);
            
                anchoCalculado = Math.max(anchoCalculado, compCelda.getPreferredSize().width);
             }

        // C. Le aplicamos el tamaño ganador a la columna, más 10 píxeles de margen estético
        columna.setPreferredWidth(anchoCalculado + 10);
        }  
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKardex = new javax.swing.JTable();
        jTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(987, 626));
        setSize(new java.awt.Dimension(987, 626));

        jPanel1.setPreferredSize(new java.awt.Dimension(987, 626));

        tblKardex.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Fecha", "Tipo", "Cantidad", "Valor Unitario", "Valor Total", "Saldo Actual", "Costo Promedio", "Saldo Actual"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKardex.setAutoscrolls(false);
        jScrollPane1.setViewportView(tblKardex);
        if (tblKardex.getColumnModel().getColumnCount() > 0) {
            tblKardex.getColumnModel().getColumn(0).setResizable(false);
            tblKardex.getColumnModel().getColumn(1).setResizable(false);
            tblKardex.getColumnModel().getColumn(2).setResizable(false);
            tblKardex.getColumnModel().getColumn(3).setResizable(false);
            tblKardex.getColumnModel().getColumn(4).setResizable(false);
            tblKardex.getColumnModel().getColumn(5).setResizable(false);
            tblKardex.getColumnModel().getColumn(6).setResizable(false);
            tblKardex.getColumnModel().getColumn(7).setResizable(false);
            tblKardex.getColumnModel().getColumn(8).setResizable(false);
        }

        jTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jTitulo.setText("Tarjeta de Almacen");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(305, Short.MAX_VALUE)
                .addComponent(jTitulo)
                .addGap(288, 288, 288))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jTitulo;
    private javax.swing.JTable tblKardex;
    // End of variables declaration//GEN-END:variables
}
